--------------------------------------------------------
--  File created - Friday-March-13-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TB_LCH_TRADE_NPV
--------------------------------------------------------

  CREATE TABLE "SDH"."TB_LCH_TRADE_NPV" 
   (	"SYS_CREAT_DTMS" DATE, 
	"SYS_CREAT_PROCSS_USR_ID" VARCHAR2(100 BYTE), 
	"SYS_UPDT_DTMS" DATE, 
	"SYS_UPDT_PROCSS_USR_ID" VARCHAR2(100 BYTE), 
	"SYS_PARTITION_ID" VARCHAR2(30 BYTE), 
	"SYS_VALUE_DATE" DATE, 
	"SYS_VALUE_TM" VARCHAR2(8 BYTE), 
	"SYS_LOAD_TIMELN_VAL" VARCHAR2(10 BYTE), 
	"SYS_LOAD_TIMELN_TIMESTAMP" DATE, 
	"DIV_NAME" VARCHAR2(30 BYTE), 
	"SYS_NAME" VARCHAR2(30 BYTE), 
	"SIT_CODE" VARCHAR2(10 BYTE), 
	"NPV_SID" NUMBER(38,0), 
	"COB_DATE" DATE, 
	"MBR_MNEMONIC" VARCHAR2(255 BYTE), 
	"SD_MNEMONIC" VARCHAR2(255 BYTE), 
	"ACCOUNT" VARCHAR2(255 BYTE), 
	"LCH_MATCHED_TRADE_REF" VARCHAR2(255 BYTE), 
	"EXTERNAL_SOURCE_REF" VARCHAR2(255 BYTE), 
	"SD_TRADE_ID" VARCHAR2(255 BYTE), 
	"CURRENCY" VARCHAR2(255 BYTE), 
	"NOTIONAL_AMOUNT" NUMBER(38,12), 
	"NPV_PREVIOUS_COB" NUMBER(38,12), 
	"CURRENT_NPV" NUMBER(38,12), 
	"PRICE_ALIGN_INT_RATE" NUMBER(38,16), 
	"TRADE_LEVEL_PAI" NUMBER(38,12), 
	"PARTICIPANT_DIRECTION" VARCHAR2(255 BYTE), 
	"ACCRUED_PAY_LEG_COUPON" NUMBER(38,16), 
	"ACCRUED_RECEIVE_LEG_COUPON" NUMBER(38,16), 
	"DIRTY_PARTITIPANT_PRICE" NUMBER(38,16), 
	"CLEAN_PARTITIPANT_PRICE" NUMBER(38,16), 
	"MARKET_NPV_PREVIOUS_COB" NUMBER(38,12), 
	"CURRENT_MARKET_NPV" NUMBER(38,12), 
	"MKT_NPV_PREV_COB_EX_UPFRONT" NUMBER(38,12), 
	"CURRENT_MARKET_NPV_EX_UPFRONT" NUMBER(38,12), 
	"DIRTY_MARKET_PRICE" NUMBER(38,16), 
	"CLEAN_PRICE_A" NUMBER(38,16), 
	"CLEAN_PRICE_A_EX_UPFRONT" NUMBER(38,16), 
	"ACCRUED_PAY_LEG_COUPON_EFFECT" NUMBER(38,16), 
	"ACCRUED_RECV_LEG_COUPON_EFFECT" NUMBER(38,16), 
	"CLEAN_PRICE_B" NUMBER(38,16), 
	"CLEAN_PRICE_B_EX_UPFRONT" NUMBER(38,16), 
	"CONSIDERATION_AMOUNT" NUMBER(38,12), 
	"CONSIDERATION_NPV" NUMBER(38,12), 
	"CONSIDERATION_DF" NUMBER(38,16), 
	"DIRTY_MARKET_PRICE_EX_UPFRONT" NUMBER(38,16), 
	"DIRTY_PRICE_EX_UPFRONT" NUMBER(38,16), 
	"EXECUTION_VENUE_TYPE" VARCHAR2(255 BYTE), 
	"EXECUTION_VENUE" VARCHAR2(255 BYTE), 
	"EXECUTION_DATE_TIME" DATE, 
	"EID" VARCHAR2(255 BYTE), 
	"LID" VARCHAR2(255 BYTE), 
	"NID" NUMBER(38,12), 
	"STANDARD_NETTING_KEY" VARCHAR2(255 BYTE), 
	"BLENDED_NETTING_KEY" VARCHAR2(255 BYTE), 
	"PAY_LEG_NPV" NUMBER(38,12), 
	"RECV_LEG_NPV" NUMBER(38,12), 
	"CLEAN_PRICE_A_EX_UPFRONT_PAY" NUMBER(38,16), 
	"CLEAN_PRICE_A_EX_UPFRONT_RECV" NUMBER(38,16), 
	"DIRTY_PRICE_PAY" NUMBER(38,16), 
	"DIRTY_PRICE_RECV" NUMBER(38,16), 
	"ACTUAL_NPV" NUMBER(38,12), 
	"PREVIOUS_ACTUAL_NPV" NUMBER(38,12), 
	"VM_TRADE_CLASSIFICATION" VARCHAR2(255 BYTE), 
	"PPS_HOLIDAY" VARCHAR2(255 BYTE), 
	"SETTLEMENT_CCY" VARCHAR2(255 BYTE), 
	"NPV_ADJUSTMENT" NUMBER(38,12), 
	"FV_NOTIONAL_AMOUNT" NUMBER(38,12), 
	"BOND_ISIN" VARCHAR2(255 BYTE), 
	"SC_COUPON_RATE" NUMBER(38,16), 
	"INFL_SC_FIX_LEG_NOTIONAL_AMT" NUMBER(38,12), 
	"VALUATION_TIMESTAMP" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
  PARTITION BY LIST ("SYS_VALUE_DATE") 
  SUBPARTITION BY LIST ("SYS_PARTITION_ID") 
 (PARTITION "P_20251030"  VALUES (TO_DATE(' 2025-10-30 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202510300102067N"  VALUES ('202510300102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251031"  VALUES (TO_DATE(' 2025-10-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202510310102067N"  VALUES ('202510310102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251103"  VALUES (TO_DATE(' 2025-11-03 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511030102067N"  VALUES ('202511030102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251104"  VALUES (TO_DATE(' 2025-11-04 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511040102067N"  VALUES ('202511040102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251105"  VALUES (TO_DATE(' 2025-11-05 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511050102067N"  VALUES ('202511050102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251106"  VALUES (TO_DATE(' 2025-11-06 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511060102067N"  VALUES ('202511060102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251107"  VALUES (TO_DATE(' 2025-11-07 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511070102067N"  VALUES ('202511070102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251110"  VALUES (TO_DATE(' 2025-11-10 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511100102067N"  VALUES ('202511100102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251111"  VALUES (TO_DATE(' 2025-11-11 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511110102067N"  VALUES ('202511110102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251112"  VALUES (TO_DATE(' 2025-11-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511120102067N"  VALUES ('202511120102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251113"  VALUES (TO_DATE(' 2025-11-13 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511130102067N"  VALUES ('202511130102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251114"  VALUES (TO_DATE(' 2025-11-14 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511140102067N"  VALUES ('202511140102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251117"  VALUES (TO_DATE(' 2025-11-17 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511170102067N"  VALUES ('202511170102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251118"  VALUES (TO_DATE(' 2025-11-18 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511180102067N"  VALUES ('202511180102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251119"  VALUES (TO_DATE(' 2025-11-19 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511190102067N"  VALUES ('202511190102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251120"  VALUES (TO_DATE(' 2025-11-20 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511200102067N"  VALUES ('202511200102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251121"  VALUES (TO_DATE(' 2025-11-21 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511210102067N"  VALUES ('202511210102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251124"  VALUES (TO_DATE(' 2025-11-24 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511240102067N"  VALUES ('202511240102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251125"  VALUES (TO_DATE(' 2025-11-25 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511250102067N"  VALUES ('202511250102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251126"  VALUES (TO_DATE(' 2025-11-26 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511260102067N"  VALUES ('202511260102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251127"  VALUES (TO_DATE(' 2025-11-27 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511270102067N"  VALUES ('202511270102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251128"  VALUES (TO_DATE(' 2025-11-28 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511280102067N"  VALUES ('202511280102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251201"  VALUES (TO_DATE(' 2025-12-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512010102067N"  VALUES ('202512010102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251202"  VALUES (TO_DATE(' 2025-12-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512020102067N"  VALUES ('202512020102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251203"  VALUES (TO_DATE(' 2025-12-03 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512030102067N"  VALUES ('202512030102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251204"  VALUES (TO_DATE(' 2025-12-04 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512040102067N"  VALUES ('202512040102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251205"  VALUES (TO_DATE(' 2025-12-05 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512050102067N"  VALUES ('202512050102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251208"  VALUES (TO_DATE(' 2025-12-08 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512080102067N"  VALUES ('202512080102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251209"  VALUES (TO_DATE(' 2025-12-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512090102067N"  VALUES ('202512090102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251210"  VALUES (TO_DATE(' 2025-12-10 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512100102067N"  VALUES ('202512100102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251211"  VALUES (TO_DATE(' 2025-12-11 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512110102067N"  VALUES ('202512110102067N') SEGMENT CREATION IMMEDIATE 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251212"  VALUES (TO_DATE(' 2025-12-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512120102067N"  VALUES ('202512120102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251215"  VALUES (TO_DATE(' 2025-12-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512150102067N"  VALUES ('202512150102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251216"  VALUES (TO_DATE(' 2025-12-16 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512160102067N"  VALUES ('202512160102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251217"  VALUES (TO_DATE(' 2025-12-17 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512170102067N"  VALUES ('202512170102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251218"  VALUES (TO_DATE(' 2025-12-18 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512180102067N"  VALUES ('202512180102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251219"  VALUES (TO_DATE(' 2025-12-19 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512190102067N"  VALUES ('202512190102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251222"  VALUES (TO_DATE(' 2025-12-22 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512220102067N"  VALUES ('202512220102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251223"  VALUES (TO_DATE(' 2025-12-23 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512230102067N"  VALUES ('202512230102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251224"  VALUES (TO_DATE(' 2025-12-24 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512240102067N"  VALUES ('202512240102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251226"  VALUES (TO_DATE(' 2025-12-26 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512260102067N"  VALUES ('202512260102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251229"  VALUES (TO_DATE(' 2025-12-29 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512290102067N"  VALUES ('202512290102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251230"  VALUES (TO_DATE(' 2025-12-30 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512300102067N"  VALUES ('202512300102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251231"  VALUES (TO_DATE(' 2025-12-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512310102067N"  VALUES ('202512310102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260102"  VALUES (TO_DATE(' 2026-01-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601020102067N"  VALUES ('202601020102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260105"  VALUES (TO_DATE(' 2026-01-05 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601050102067N"  VALUES ('202601050102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260106"  VALUES (TO_DATE(' 2026-01-06 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601060102067N"  VALUES ('202601060102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260107"  VALUES (TO_DATE(' 2026-01-07 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601070102067N"  VALUES ('202601070102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260108"  VALUES (TO_DATE(' 2026-01-08 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601080102067N"  VALUES ('202601080102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260109"  VALUES (TO_DATE(' 2026-01-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601090102067N"  VALUES ('202601090102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260112"  VALUES (TO_DATE(' 2026-01-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601120102067N"  VALUES ('202601120102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260113"  VALUES (TO_DATE(' 2026-01-13 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601130102067N"  VALUES ('202601130102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260114"  VALUES (TO_DATE(' 2026-01-14 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601140102067N"  VALUES ('202601140102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260115"  VALUES (TO_DATE(' 2026-01-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601150102067N"  VALUES ('202601150102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260116"  VALUES (TO_DATE(' 2026-01-16 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601160102067N"  VALUES ('202601160102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260119"  VALUES (TO_DATE(' 2026-01-19 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601190102067N"  VALUES ('202601190102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260120"  VALUES (TO_DATE(' 2026-01-20 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601200102067N"  VALUES ('202601200102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260121"  VALUES (TO_DATE(' 2026-01-21 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601210102067N"  VALUES ('202601210102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260122"  VALUES (TO_DATE(' 2026-01-22 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601220102067N"  VALUES ('202601220102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260123"  VALUES (TO_DATE(' 2026-01-23 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601230102067N"  VALUES ('202601230102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260126"  VALUES (TO_DATE(' 2026-01-26 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601260102067N"  VALUES ('202601260102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260127"  VALUES (TO_DATE(' 2026-01-27 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601270102067N"  VALUES ('202601270102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260128"  VALUES (TO_DATE(' 2026-01-28 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601280102067N"  VALUES ('202601280102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260129"  VALUES (TO_DATE(' 2026-01-29 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601290102067N"  VALUES ('202601290102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260130"  VALUES (TO_DATE(' 2026-01-30 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601300102067N"  VALUES ('202601300102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260202"  VALUES (TO_DATE(' 2026-02-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202602020102067N"  VALUES ('202602020102067N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) ) ;

   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."SYS_CREAT_DTMS" IS 'Record creation date';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."SYS_CREAT_PROCSS_USR_ID" IS 'Record creation user';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."SYS_UPDT_DTMS" IS 'Record update date';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."SYS_UPDT_PROCSS_USR_ID" IS 'Record update user';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."SYS_PARTITION_ID" IS 'Partition ID';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."SYS_VALUE_DATE" IS 'Business Value date';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."SYS_VALUE_TM" IS 'Running actual time';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."SYS_LOAD_TIMELN_VAL" IS 'Load timeline (EOD, CORR, )';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."SYS_LOAD_TIMELN_TIMESTAMP" IS 'Run date of the extract on Murex side';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."DIV_NAME" IS 'Division name';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."SYS_NAME" IS 'System name';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."SIT_CODE" IS 'Site code';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."COB_DATE" IS 'Closing Date';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."MBR_MNEMONIC" IS 'SwapClear Member ID';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."SD_MNEMONIC" IS 'Swapclear Party Identifier (This is either a real Bic code or a short code constructed from party name) ';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."ACCOUNT" IS 'Clearing account used  H  - House';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."LCH_MATCHED_TRADE_REF" IS 'The Clearing House Trade Reference';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."EXTERNAL_SOURCE_REF" IS 'The trade source''s reference,  For Economic Amendment - offset trade has a suffix of _1 , replacement trade a suffix of -2 (without the LCH000 prefix)  eg, 123456_1 / 123456_2';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."SD_TRADE_ID" IS 'Clearing Member internal Trade ID, unless the Clearing Member did not input their trade ID, then this is populated with the ExternalSourceRef trade ID';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."CURRENCY" IS 'ISO Standard Alphabetic Currency Code';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."NOTIONAL_AMOUNT" IS 'Trade notional amount in currency of the original trade (Local Currency), For VNS this will show the Notional applying to the first period, it will not change during the life of the swap,';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."NPV_PREVIOUS_COB" IS 'Trade Level NPV for the previous End of Day,  This will be blank if the trade is a new trade received today, Non Deliverable swaps will report NPV in USD not trade ccy';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."CURRENT_NPV" IS 'Cumulative NPV at the current time ie At the time of the latest revaluation, Non Deliverable swaps will report NPV in USD not trade ccy';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."PRICE_ALIGN_INT_RATE" IS 'Price Alignment Interest Rate for CTM trades or Price Alignment Amount Rate for STM trades as a fraction';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."TRADE_LEVEL_PAI" IS 'Price alignment interest  for CTM trades or Price Alignment Amount for STM trades
In report suffixes a, b and c the PAI/PAA amount is null, Non Deliverable swaps will report PAI in USD not trade ccy';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."PARTICIPANT_DIRECTION" IS 'Direction of the swap (long or short) from the perspective of the report recipient
For fixed/float and OIS, you are long when you receive fixed,
For FRAs, you are long when you buy the FRA';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."ACCRUED_PAY_LEG_COUPON" IS 'Accrued coupon on the pay leg, accrual calculation starts on T+1, The difference between  AccruedPayLegCoupon and AccruedPayLegCouponEffective? This is just a difference in when the first day of accrual starts in our calculation,  For AccruedPayLegCouponEffective, we assume that accrual starts on effective date,  For AccruedPayLegCoupon we assume that accrual starts on Effective Date +1, thus always being behind one day of accrual from AccruedPayLegCouponEffective,Non Deliverable swaps will report Coupon in USD not trade ccy
';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."ACCRUED_RECEIVE_LEG_COUPON" IS 'Accrued coupon on the receive leg, accrual calculation starts on T+1, Non Deliverable swaps will report Coupon in USD not trade ccy';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."DIRTY_PARTITIPANT_PRICE" IS 'Dirty price of the contract using LCH NPV (dropping cashflows on instruction)';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."CLEAN_PARTITIPANT_PRICE" IS 'Clean price including upfront fees using LCH NPV and accrual starting on T + 1';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."MARKET_NPV_PREVIOUS_COB" IS 'Trade Level NPV for the previous End of Day using market NPV (adding in dropped cashflows)
MarketNPV includes any instructed cashflows i,e, coupons or considerations,  Instructed cashflows fall out on payment date, Non Deliverable swaps will report NPV in USD not trade ccy';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."CURRENT_MARKET_NPV" IS 'Trade Level NPV at the current time i,e, at the time of the latest revaluation using market NPV,
MarketNPV includes any instructed cashflows i,e, coupons or considerations,  Instructed cashflows fall out on payment date, CurrentMarketNPV will include the NPV of any instructed cashflows until payment date,Non Deliverable swaps will report NPV in USD not trade ccy';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."MKT_NPV_PREV_COB_EX_UPFRONT" IS 'Trade Level NPV ex discounted upfront fee for the previous End of Day using "market NPV" (adding in dropped coupons) ,Non Deliverable swaps will report NPV in USD not trade ccy';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."CURRENT_MARKET_NPV_EX_UPFRONT" IS 'SwapClear report market calculated NPVs with the discounted value of the sum of upfront fees removed from the calculation, Please note, in the event that there are multiple fees, the field removes the sum of all discounted upfront fees,],Non Deliverable swaps will report NPV in USD not trade ccy';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."DIRTY_MARKET_PRICE" IS 'Dirty price of the contract using market NPV (adding in dropped cashflows)';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."CLEAN_PRICE_A" IS 'Clean price including upfront fees using market NPV (adding in dropped cashflows) and removing accruals starting on T ';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."CLEAN_PRICE_A_EX_UPFRONT" IS 'Clean price ex discounted upfront fee using market NPV (adding in dropped cashflows) and removing accruals starting on T ';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."ACCRUED_PAY_LEG_COUPON_EFFECT" IS 'Accrued coupon on the pay leg, accrual calculation starts on T,Non Deliverable swaps will report Coupon in USD not trade ccy';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."ACCRUED_RECV_LEG_COUPON_EFFECT" IS 'Accrued coupon on the receive leg, accrual calculation starts on T, Non Deliverable swaps will report Coupon in USD not trade ccy';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."CLEAN_PRICE_B" IS 'Clean price including upfront fees using market NPV (adding in dropped cashflows) and removing accruals starting on T + 1';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."CLEAN_PRICE_B_EX_UPFRONT" IS 'Clean price ex discounted upfront fee using market NPV (adding in dropped cashflows) and removing accruals starting on T + 1';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."CONSIDERATION_AMOUNT" IS 'Amount of consideration';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."CONSIDERATION_NPV" IS 'NPV of next paying fee -- will fall off after payment, if multiple fees on same payment date, then field will reflect the sum of the NPV for those fees, Non Deliverable swaps will report NPV in USD not trade ccy';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."CONSIDERATION_DF" IS 'Fee discount factor of next paying fee(s) -- will fall off after payment  ';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."DIRTY_MARKET_PRICE_EX_UPFRONT" IS 'Dirty price of the contract using market NPV (adding in dropped cashflows and excluding upfront fees)';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."DIRTY_PRICE_EX_UPFRONT" IS 'Dirty price of the contract using LCH NPV (dropping cashflows on instruction and excluding upfront fees)';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."EXECUTION_VENUE_TYPE" IS 'The type of market where the trade was executed, One of:
 - SEF
 - Off-Facility
 - DCM';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."EXECUTION_VENUE" IS 'The facility, exchange, or market where the trade was executed, ';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."EXECUTION_DATE_TIME" IS 'The date and time the trade was executed on the trading venue,';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."EID" IS 'Economic Identifier of the Trade';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."LID" IS 'LCH Standard Netting Identifier for a trade with a unsettled front stub,
Format:
    NULL - If front stub is settled; or
    NULL - If trade does not have a front stub; or
    LID - If front stub unsettled';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."NID" IS 'LCH Netting Identifier used for both future cashflow and blended rate netting, Each trade is assigned a NID which is common between trades with the same economic profile, ';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."STANDARD_NETTING_KEY" IS 'The key used by LCH for Standard Netting,
Format:
    LID  - if unsettled front stub; or
    NID + "_" ++ Leg1  Accrual Start Date for next unrealised fixed flow_Next  Payment Date for next unrealised fixed flow + "_" + Leg2 Accrual Start Date for next unrealised Float Flow_ Next Payment Date for unrealised Float Flow   +  "_" + Decimalised Fixed Rate,
    E,g,
    12345_20140206_20150206_20140206_20140806_0,000566';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."BLENDED_NETTING_KEY" IS 'The key used by LCH for Blended Netting,
Format:
    NULL - if the product type is not eligible for  blended netting; or
    NULL - if unsettled front stub; or
    NID + "_" + Leg1  Accrual Start Date for next unrealised fixed flow_Next  Payment Date for next unrealised fixed flow + "_" + Leg2 Accrual Start Date for next unrealised Float Flow_ Next Payment Date for unrealised Float Flow
   E,g,
    12345_20140206_20150206_20140206_20140806';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."PAY_LEG_NPV" IS 'Field will display the summed discounted cashflows for the pay leg only,  Value will reflect LCH NPV, cashflows will be dropped on instruction date, Non Deliverable swaps will report Coupon in USD not trade ccy    ';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."RECV_LEG_NPV" IS 'Field will display the summed discounted cashflows for the receive leg only,  Value will reflect LCH NPV, cashflows will be dropped on instruction date, Non Deliverable swaps will report Coupon in USD not trade ccy    ';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."CLEAN_PRICE_A_EX_UPFRONT_PAY" IS 'Clean price ex discounted upfrong fee using Pay Leg NPV (cashflows will be dropped on instruction date) and accruals starting on T ';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."CLEAN_PRICE_A_EX_UPFRONT_RECV" IS 'Clean price ex discounted upfrong fee using Receive Leg NPV (cashflows will be dropped on instruction date) and accruals starting on T ';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."DIRTY_PRICE_PAY" IS 'Dirty price of the contract using Pay Leg NPV (cashflows will be dropped on instruction date) ';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."DIRTY_PRICE_RECV" IS 'Dirty price of the contract using Rec Leg NPV (cashflows will be dropped on instruction date) ';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."ACTUAL_NPV" IS 'Close of Business Settled to Market (STM) NPV amount or Close of Business Collateralised to Market (CTM) NPV amount, STM NPV is only populated in the ''f'' version of the report for STM trades,Non Deliverable swaps will report Coupon in USD not trade ccy';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."PREVIOUS_ACTUAL_NPV" IS 'Previous Close of Business Settled to Market NPV amount for STM trades or Previous Close of Business Collateralised to Market NPV amount for CTM trades, STM NPV is only populated in the ''f'' version of the report for STM trades, Non Deliverable swaps will report Coupon in USD not trade ccy';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."VM_TRADE_CLASSIFICATION" IS 'Trade level classification ie CTM, STM or Null';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."PPS_HOLIDAY" IS 'Y denotes wether the currency referenced is on Holiday next good business day ';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."SETTLEMENT_CCY" IS 'ISO Standard Alphabetic Currency Code';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."NPV_ADJUSTMENT" IS 'Reversal of previous day closing NPV figure, expressed as a Debit or Credit';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."FV_NOTIONAL_AMOUNT" IS 'Future Value Notional';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."BOND_ISIN" IS 'Valid ISIN format';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."SC_COUPON_RATE" IS 'Coupon rate applied to bond';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."INFL_SC_FIX_LEG_NOTIONAL_AMT" IS 'Trade notional amount applicable to the Fixed Leg in currency of the SCIS ''Proceeds'' ProductType';
   COMMENT ON COLUMN "SDH"."TB_LCH_TRADE_NPV"."VALUATION_TIMESTAMP" IS 'Date and time of the trade valuation in UTC';
   COMMENT ON TABLE "SDH"."TB_LCH_TRADE_NPV"  IS 'Trade level Net Present Value attributes';
--------------------------------------------------------
--  Constraints for Table TB_LCH_TRADE_NPV
--------------------------------------------------------

  ALTER TABLE "SDH"."TB_LCH_TRADE_NPV" MODIFY ("SYS_CREAT_DTMS" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_LCH_TRADE_NPV" MODIFY ("SYS_CREAT_PROCSS_USR_ID" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_LCH_TRADE_NPV" MODIFY ("SYS_PARTITION_ID" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_LCH_TRADE_NPV" MODIFY ("SYS_VALUE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_LCH_TRADE_NPV" MODIFY ("SYS_VALUE_TM" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_LCH_TRADE_NPV" MODIFY ("SYS_LOAD_TIMELN_VAL" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_LCH_TRADE_NPV" MODIFY ("NPV_SID" NOT NULL ENABLE);
