--------------------------------------------------------
--  File created - Saturday-February-21-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TB_SMARTCO_COUNTERPARTY
--------------------------------------------------------

  CREATE TABLE "SDH"."TB_SMARTCO_COUNTERPARTY" 
   (	"SYS_CREAT_DTMS" DATE DEFAULT SYSDATE, 
	"SYS_CREAT_PROCSS_USR_ID" VARCHAR2(100 BYTE), 
	"SYS_UPDT_DTMS" DATE, 
	"SYS_UPDT_PROCSS_USR_ID" VARCHAR2(100 BYTE), 
	"SYS_PARTITION_ID" VARCHAR2(30 BYTE), 
	"RPY_VALUE_DATE" DATE, 
	"RPY_VALUE_TM" VARCHAR2(8 BYTE), 
	"RPY_LOAD_TIMELN_VAL" VARCHAR2(10 BYTE), 
	"DIV_NAME" VARCHAR2(30 BYTE), 
	"SYS_NAME" VARCHAR2(30 BYTE), 
	"SIT_CODE" VARCHAR2(10 BYTE), 
	"RPY_SID" NUMBER(38,0), 
	"AGENT_ID" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(255 BYTE), 
	"LEI" VARCHAR2(255 BYTE), 
	"HQ_COUNTRY" VARCHAR2(50 BYTE), 
	"INC_COUNTRY" VARCHAR2(50 BYTE), 
	"PARENT_CNY" NUMBER(38,16), 
	"ULTIMATE_PARENT_CNY" NUMBER(38,16), 
	"MUREX_COUNTERPART" VARCHAR2(255 BYTE), 
	"MUREX_AGENT_ID" VARCHAR2(255 BYTE), 
	"MIDAS_PARENT" VARCHAR2(50 BYTE), 
	"MIDAS_CHILD" VARCHAR2(50 BYTE), 
	"BBG_CODE" VARCHAR2(255 BYTE), 
	"REUTERS_CODE" VARCHAR2(255 BYTE), 
	"ISM_CODE" VARCHAR2(255 BYTE), 
	"FCC_NUMBER" VARCHAR2(255 BYTE), 
	"JPM_NO" VARCHAR2(255 BYTE), 
	"JPM_MUREX_PTF" VARCHAR2(255 BYTE), 
	"TRW_CODE" VARCHAR2(255 BYTE), 
	"LCH_BIC_CODE" VARCHAR2(255 BYTE), 
	"ID_DTCC" VARCHAR2(50 BYTE), 
	"TAX_ID" VARCHAR2(50 BYTE), 
	"REPORTING_SA_US" VARCHAR2(50 BYTE), 
	"REPORTING_SA_EU" VARCHAR2(50 BYTE), 
	"REPORTING_SA_CAN" VARCHAR2(50 BYTE), 
	"REPORTING_DELEGATION" VARCHAR2(50 BYTE), 
	"OTC_CTPY_TYPE" VARCHAR2(50 BYTE), 
	"EMIR_STATUS_MX" VARCHAR2(50 BYTE), 
	"COUNTERPARTY_ROLE_OTC_REP" VARCHAR2(50 BYTE), 
	"ALBERTA" VARCHAR2(50 BYTE), 
	"BRITISH_COLUMBIA" VARCHAR2(50 BYTE), 
	"CANADA" VARCHAR2(50 BYTE), 
	"MANITOBA" VARCHAR2(50 BYTE), 
	"NEW_BRUNSWICK" VARCHAR2(50 BYTE), 
	"NEWFOUNDLAND_AND_LABRADOR" VARCHAR2(50 BYTE), 
	"NORTHWEST_TERRITORIES" VARCHAR2(50 BYTE), 
	"NOVA_SCOTIA" VARCHAR2(50 BYTE), 
	"NUNAVUT" VARCHAR2(50 BYTE), 
	"ONTARIO" VARCHAR2(50 BYTE), 
	"PRINCE_EDWARD_ISLAND" VARCHAR2(50 BYTE), 
	"QUEBEC" VARCHAR2(50 BYTE), 
	"SASKATCHEWAN" VARCHAR2(50 BYTE), 
	"YUKON" VARCHAR2(50 BYTE), 
	"ACCESS_RIGHTS" VARCHAR2(255 BYTE), 
	"CLS_ENABLED" VARCHAR2(255 BYTE), 
	"CORPORATE_SECTOR" VARCHAR2(255 BYTE), 
	"FBN_CUSTOMER_TP" VARCHAR2(255 BYTE), 
	"GSD_REPO" VARCHAR2(255 BYTE), 
	"GSD_SERVIC" VARCHAR2(255 BYTE), 
	"JPM_MX" VARCHAR2(255 BYTE), 
	"LINKED_COMMERCIAL_ACTIVITY" VARCHAR2(255 BYTE), 
	"PRINT_BS" VARCHAR2(255 BYTE), 
	"SSA" VARCHAR2(255 BYTE), 
	"STATUS_MQ" VARCHAR2(255 BYTE), 
	"STANDARD_ID" NUMBER(38,16), 
	"ISM_CASH_ACC_CAD" VARCHAR2(50 BYTE), 
	"ISM_CASH_ACC_USD" VARCHAR2(50 BYTE), 
	"SHORT_MIDAS_OCT" VARCHAR2(255 BYTE), 
	"AGENT_CREATION_DATE" DATE, 
	"AGENT_PURPOSE" VARCHAR2(255 BYTE), 
	"US_DETERMINATION_STATUS" VARCHAR2(255 BYTE), 
	"DF_CFTC_SWAP_ONBOARDING" VARCHAR2(255 BYTE), 
	"DF_SEC_SWAP_ONBOARDING" VARCHAR2(255 BYTE), 
	"AFFILT_CONDUIT_REPRESENTATION" VARCHAR2(255 BYTE), 
	"US_GUARANTEE_REPRESENTATION" VARCHAR2(255 BYTE), 
	"LEI_STATUS" VARCHAR2(255 BYTE), 
	"SWAP_DEALER_FLAG" VARCHAR2(255 BYTE), 
	"SB_SWAP_DEALER_FLAG" VARCHAR2(255 BYTE), 
	"MSP_FLAG" VARCHAR2(255 BYTE), 
	"MSBSP_FLAG" VARCHAR2(255 BYTE), 
	"FINANCIAL_ENTITY" VARCHAR2(255 BYTE), 
	"ORAL_PTMM_ELECTION" VARCHAR2(255 BYTE), 
	"PTMM_EXEMPTION_COVERED_FX" VARCHAR2(255 BYTE), 
	"PTMM_EXEMPT_COVR_DERIVATIVES" VARCHAR2(255 BYTE), 
	"PTMM_EXEMPTION_OTHER" VARCHAR2(255 BYTE), 
	"DF_EMAIL_PORTFOLIO_DATA" VARCHAR2(1000 BYTE), 
	"CLEARING_EXCEPTION_FE" VARCHAR2(255 BYTE), 
	"CLEARING_EXCEPTION_NFE" VARCHAR2(255 BYTE), 
	"PORTFOLIO_DATA_EXCHANGE_MODE" VARCHAR2(255 BYTE), 
	"EMAIL_DAILY_MARKS" VARCHAR2(255 BYTE), 
	"CANADIAN_DERIVATIVE_STATUS" VARCHAR2(255 BYTE), 
	"CP_ATTENTION_TO" VARCHAR2(255 BYTE), 
	"CP_CITY_STATE_ZIPCODE" VARCHAR2(255 BYTE), 
	"CP_CIVIC_ADDRESS" VARCHAR2(255 BYTE), 
	"PART20_102SFORM_REPORTED" VARCHAR2(255 BYTE), 
	"ACTIVATION" VARCHAR2(255 BYTE), 
	"GCC_NUMBER" VARCHAR2(255 BYTE), 
	"WEB_CURRENCY_SET" VARCHAR2(255 BYTE), 
	"WEB_PRICING_SET" VARCHAR2(255 BYTE), 
	"ALPHA_CP_ONLY" VARCHAR2(255 BYTE), 
	"PART20_UPDATE_DATE" DATE, 
	"PAYMENT_NETTING" VARCHAR2(255 BYTE), 
	"DAYLIGHT_LIMIT" NUMBER(38,16), 
	"ENTITY_NAME" VARCHAR2(255 BYTE), 
	"BANK_ROLE" VARCHAR2(255 BYTE), 
	"BIC_CODE" VARCHAR2(30 BYTE), 
	"SENDER_PARTY" CHAR(1 BYTE), 
	"REL_ENTITY_STATUS" CHAR(1 BYTE), 
	"GUARANTOR_LEI" VARCHAR2(255 BYTE), 
	"INSTITUTIONAL_CP" CHAR(1 BYTE), 
	"EVAL_AGENT_NAME" VARCHAR2(255 BYTE), 
	"EVAL_AGENT_EMAIL" VARCHAR2(255 BYTE), 
	"EVAL_AGENT_PHONE" VARCHAR2(30 BYTE), 
	"SUPRANATIONAL" CHAR(1 BYTE), 
	"US_PERSON" CHAR(1 BYTE), 
	"EMIR_RECON_EXEMPT" CHAR(1 BYTE), 
	"BROKER" CHAR(1 BYTE), 
	"ELECTRONIC_PLATFORM" CHAR(1 BYTE), 
	"INTERNAL_ROLE" CHAR(1 BYTE), 
	"SEC_PORTF_RECON_EXEMPTION" CHAR(1 BYTE), 
	"PNC_BU_ID" VARCHAR2(150 BYTE), 
	"CLR_EX_END_USER_EXCEPTION" CHAR(1 BYTE), 
	"CLR_EX_INT_AFF_EXEMPTION" CHAR(1 BYTE), 
	"CLR_EX_SMALL_BK_EXEMPTION" CHAR(1 BYTE), 
	"CLR_EX_COOP_EXEMPTION" CHAR(1 BYTE), 
	"CLR_EX_NO_ACT_LETTER" CHAR(1 BYTE), 
	"CLR_EX_OTHER_EXCEPTIONS" CHAR(1 BYTE), 
	"FED_ENTITY_INDICATOR" CHAR(1 BYTE), 
	"PLATFORM_ID_TYPE" VARCHAR2(100 BYTE), 
	"MIC" VARCHAR2(100 BYTE), 
	"AFF_CPTY_MARG_CAP_INDICATOR" CHAR(1 BYTE), 
	"CPTY_ID_SOURCE_NAT_PERS_IND" CHAR(1 BYTE), 
	"CPTY_ID_SOURCE_PRIV_LAW_IDENT" CHAR(1 BYTE), 
	"SFTR_UTI_SCENARIO" VARCHAR2(255 BYTE), 
	"CPTY_ID_SRC_PRIVLAW_ID_BOI" CHAR(1 BYTE), 
	"BNC_ID" VARCHAR2(255 BYTE), 
	"FUND_MANAGER" VARCHAR2(255 BYTE), 
	"TICKER" VARCHAR2(255 BYTE), 
	"NRA_TAX_POOL" VARCHAR2(100 BYTE), 
	"CORPORATE_SECTOR_FC" VARCHAR2(255 BYTE), 
	"CORPORATE_SECTOR_NFC" VARCHAR2(255 BYTE), 
	"CLEARING_THRESHOLD_EXEEDED" CHAR(1 BYTE), 
	"UK_VS_EU_BASED" VARCHAR2(255 BYTE), 
	"OPT_OUT_EMIR_REPORTING" CHAR(1 BYTE), 
	"EMIR_PORTFOLIO_RECON_ELECTIONS" VARCHAR2(255 BYTE), 
	"ESMA_INTRA_CLRNG_EXEMPTION" CHAR(1 BYTE), 
	"CLIENT_MANAGEMENT" VARCHAR2(255 BYTE), 
	"CLIENT_PLATFORM" VARCHAR2(255 BYTE), 
	"EMIR_EU_ONBOARDING" VARCHAR2(255 BYTE), 
	"EMIR_REPORTING_OBLIGATION" VARCHAR2(255 BYTE), 
	"CBCR_DERIVATIVE_PARTY_TYPE" VARCHAR2(255 BYTE), 
	"CBCR_WAIVER" VARCHAR2(255 BYTE), 
	"CBCR_VERIFICATION_TYPE" VARCHAR2(255 BYTE), 
	"CBCR_NAV" VARCHAR2(255 BYTE), 
	"HKMA_PROF_INVESTORS_TYPE" VARCHAR2(255 BYTE), 
	"HKMA_ONBOARDING_STATUS" VARCHAR2(255 BYTE), 
	"US_CP_SCORE" VARCHAR2(255 BYTE), 
	"INVESTMENT_MANAGER" CHAR(1 BYTE), 
	"EXECUTION_AGENT" VARCHAR2(255 BYTE), 
	"SEF_ONLY" VARCHAR2(255 BYTE), 
	"HKMA_CORP_SECTOR" VARCHAR2(255 BYTE), 
	"HKMA_CLASSIFICATION" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 ROW STORE COMPRESS ADVANCED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
  PARTITION BY LIST ("RPY_VALUE_DATE") 
  SUBPARTITION BY LIST ("SYS_PARTITION_ID") 
 (PARTITION "P_20251030"  VALUES (TO_DATE(' 2025-10-30 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202510300101045N"  VALUES ('202510300101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251031"  VALUES (TO_DATE(' 2025-10-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202510310101045N"  VALUES ('202510310101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251103"  VALUES (TO_DATE(' 2025-11-03 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511030101045N"  VALUES ('202511030101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251104"  VALUES (TO_DATE(' 2025-11-04 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511040101045N"  VALUES ('202511040101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251105"  VALUES (TO_DATE(' 2025-11-05 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511050101045N"  VALUES ('202511050101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251106"  VALUES (TO_DATE(' 2025-11-06 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511060101045N"  VALUES ('202511060101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251107"  VALUES (TO_DATE(' 2025-11-07 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511070101045N"  VALUES ('202511070101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251110"  VALUES (TO_DATE(' 2025-11-10 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511100101045N"  VALUES ('202511100101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251111"  VALUES (TO_DATE(' 2025-11-11 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511110101045N"  VALUES ('202511110101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251112"  VALUES (TO_DATE(' 2025-11-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511120101045N"  VALUES ('202511120101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251113"  VALUES (TO_DATE(' 2025-11-13 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511130101045N"  VALUES ('202511130101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251114"  VALUES (TO_DATE(' 2025-11-14 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511140101045N"  VALUES ('202511140101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251117"  VALUES (TO_DATE(' 2025-11-17 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511170101045N"  VALUES ('202511170101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251118"  VALUES (TO_DATE(' 2025-11-18 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511180101045N"  VALUES ('202511180101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251119"  VALUES (TO_DATE(' 2025-11-19 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511190101045N"  VALUES ('202511190101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251120"  VALUES (TO_DATE(' 2025-11-20 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511200101045N"  VALUES ('202511200101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251121"  VALUES (TO_DATE(' 2025-11-21 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511210101045N"  VALUES ('202511210101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251124"  VALUES (TO_DATE(' 2025-11-24 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511240101045N"  VALUES ('202511240101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251125"  VALUES (TO_DATE(' 2025-11-25 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511250101045N"  VALUES ('202511250101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251126"  VALUES (TO_DATE(' 2025-11-26 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511260101045N"  VALUES ('202511260101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251127"  VALUES (TO_DATE(' 2025-11-27 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511270101045N"  VALUES ('202511270101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251128"  VALUES (TO_DATE(' 2025-11-28 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511280101045N"  VALUES ('202511280101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251201"  VALUES (TO_DATE(' 2025-12-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512010101045N"  VALUES ('202512010101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251202"  VALUES (TO_DATE(' 2025-12-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512020101045N"  VALUES ('202512020101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251203"  VALUES (TO_DATE(' 2025-12-03 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512030101045N"  VALUES ('202512030101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251204"  VALUES (TO_DATE(' 2025-12-04 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512040101045N"  VALUES ('202512040101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251205"  VALUES (TO_DATE(' 2025-12-05 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512050101045N"  VALUES ('202512050101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251208"  VALUES (TO_DATE(' 2025-12-08 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512080101045N"  VALUES ('202512080101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251209"  VALUES (TO_DATE(' 2025-12-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512090101045N"  VALUES ('202512090101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251210"  VALUES (TO_DATE(' 2025-12-10 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512100101045N"  VALUES ('202512100101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251211"  VALUES (TO_DATE(' 2025-12-11 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512110101045N"  VALUES ('202512110101045N') SEGMENT CREATION IMMEDIATE 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251212"  VALUES (TO_DATE(' 2025-12-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512120101045N"  VALUES ('202512120101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251215"  VALUES (TO_DATE(' 2025-12-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512150101045N"  VALUES ('202512150101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251216"  VALUES (TO_DATE(' 2025-12-16 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512160101045N"  VALUES ('202512160101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251217"  VALUES (TO_DATE(' 2025-12-17 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512170101045N"  VALUES ('202512170101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251218"  VALUES (TO_DATE(' 2025-12-18 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512180101045N"  VALUES ('202512180101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251219"  VALUES (TO_DATE(' 2025-12-19 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512190101045N"  VALUES ('202512190101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251222"  VALUES (TO_DATE(' 2025-12-22 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512220101045N"  VALUES ('202512220101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251223"  VALUES (TO_DATE(' 2025-12-23 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512230101045N"  VALUES ('202512230101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251224"  VALUES (TO_DATE(' 2025-12-24 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512240101045N"  VALUES ('202512240101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251226"  VALUES (TO_DATE(' 2025-12-26 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512260101045N"  VALUES ('202512260101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251229"  VALUES (TO_DATE(' 2025-12-29 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512290101045N"  VALUES ('202512290101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251230"  VALUES (TO_DATE(' 2025-12-30 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512300101045N"  VALUES ('202512300101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251231"  VALUES (TO_DATE(' 2025-12-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512310101045N"  VALUES ('202512310101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260102"  VALUES (TO_DATE(' 2026-01-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601020101045N"  VALUES ('202601020101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260105"  VALUES (TO_DATE(' 2026-01-05 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601050101045N"  VALUES ('202601050101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260106"  VALUES (TO_DATE(' 2026-01-06 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601060101045N"  VALUES ('202601060101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260107"  VALUES (TO_DATE(' 2026-01-07 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601070101045N"  VALUES ('202601070101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260108"  VALUES (TO_DATE(' 2026-01-08 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601080101045N"  VALUES ('202601080101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260109"  VALUES (TO_DATE(' 2026-01-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601090101045N"  VALUES ('202601090101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260112"  VALUES (TO_DATE(' 2026-01-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601120101045N"  VALUES ('202601120101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260113"  VALUES (TO_DATE(' 2026-01-13 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601130101045N"  VALUES ('202601130101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260114"  VALUES (TO_DATE(' 2026-01-14 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601140101045N"  VALUES ('202601140101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260115"  VALUES (TO_DATE(' 2026-01-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601150101045N"  VALUES ('202601150101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260116"  VALUES (TO_DATE(' 2026-01-16 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601160101045N"  VALUES ('202601160101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260119"  VALUES (TO_DATE(' 2026-01-19 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601190101045N"  VALUES ('202601190101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260120"  VALUES (TO_DATE(' 2026-01-20 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601200101045N"  VALUES ('202601200101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260121"  VALUES (TO_DATE(' 2026-01-21 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601210101045N"  VALUES ('202601210101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260122"  VALUES (TO_DATE(' 2026-01-22 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601220101045N"  VALUES ('202601220101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260123"  VALUES (TO_DATE(' 2026-01-23 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601230101045N"  VALUES ('202601230101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260126"  VALUES (TO_DATE(' 2026-01-26 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601260101045N"  VALUES ('202601260101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260127"  VALUES (TO_DATE(' 2026-01-27 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601270101045N"  VALUES ('202601270101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260128"  VALUES (TO_DATE(' 2026-01-28 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601280101045N"  VALUES ('202601280101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260129"  VALUES (TO_DATE(' 2026-01-29 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601290101045N"  VALUES ('202601290101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260130"  VALUES (TO_DATE(' 2026-01-30 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601300101045N"  VALUES ('202601300101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260202"  VALUES (TO_DATE(' 2026-02-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202602020101045N"  VALUES ('202602020101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) ) ;

   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."SHORT_MIDAS_OCT" IS 'Short Name Midas (OCT).';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."AGENT_CREATION_DATE" IS 'Agent Creation Date.';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."AGENT_PURPOSE" IS 'The Classification Group Code of which Classification Type Code = Counterparty Purpose.';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."US_DETERMINATION_STATUS" IS 'US Determination Status';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."DF_CFTC_SWAP_ONBOARDING" IS 'DF/CFTC-Swap Onboarding Status';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."DF_SEC_SWAP_ONBOARDING" IS 'DF/SEC-Swap Onboarding Status';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."AFFILT_CONDUIT_REPRESENTATION" IS 'Affiliate Conduit Representation';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."US_GUARANTEE_REPRESENTATION" IS 'US Guarantee';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."LEI_STATUS" IS 'Entity Status LEI (GLEIF)';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."SWAP_DEALER_FLAG" IS 'Swap Dealer';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."SB_SWAP_DEALER_FLAG" IS 'Security Based Swap Dealer';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."MSP_FLAG" IS 'Major Swap Participant';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."MSBSP_FLAG" IS 'Major Security Based Swap Participant';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."FINANCIAL_ENTITY" IS 'Financial Entity';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."ORAL_PTMM_ELECTION" IS 'Oral PTMM Eligibility';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."PTMM_EXEMPTION_COVERED_FX" IS 'PTMM Exemption - Covered Forex';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."PTMM_EXEMPT_COVR_DERIVATIVES" IS 'PTMM Exemption - Covered Derivatives';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."PTMM_EXEMPTION_OTHER" IS 'PTMM Exemption - Other Transactions';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."DF_EMAIL_PORTFOLIO_DATA" IS 'Portfolio Data - Email Address';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CLEARING_EXCEPTION_FE" IS 'Clearing Exception - Financial Entity';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CLEARING_EXCEPTION_NFE" IS 'Clearing Exception - Non-Financial Entity';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."PORTFOLIO_DATA_EXCHANGE_MODE" IS 'Portfolio Exchange Mode';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."EMAIL_DAILY_MARKS" IS 'Daily Marks - Email Address';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CANADIAN_DERIVATIVE_STATUS" IS 'Canadian Derivative Status';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CP_ATTENTION_TO" IS 'Attention to (Address 1)';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CP_CITY_STATE_ZIPCODE" IS 'City State Zip Code (Address 2)';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CP_CIVIC_ADDRESS" IS 'Civic Address (Address 3)';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."PART20_102SFORM_REPORTED" IS 'Part-20 Reported';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."ACTIVATION" IS 'Activation (live-dead-suspend)';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."GCC_NUMBER" IS 'GCC number';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."WEB_CURRENCY_SET" IS 'Currency Set';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."WEB_PRICING_SET" IS 'Pricing Set';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."ALPHA_CP_ONLY" IS 'Alpha counterparty only';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."PART20_UPDATE_DATE" IS 'Part-20 Reported status update date.';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."PAYMENT_NETTING" IS 'payment netting status';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."DAYLIGHT_LIMIT" IS 'Maximum Amount of the total transaction permitted daily (Notional Transaction in CAD)';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."ENTITY_NAME" IS 'Name of the Entity';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."BANK_ROLE" IS 'Does the CP have the Role of Bank';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."BIC_CODE" IS 'Swift Number assigned with the Headquarters Address';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."SENDER_PARTY" IS 'Confirmation Sender Party';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."REL_ENTITY_STATUS" IS 'Relying Entity Status';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."GUARANTOR_LEI" IS 'Guarantor LEI';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."INSTITUTIONAL_CP" IS 'Institutional CP';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."EVAL_AGENT_NAME" IS 'Designated Evaluation Agent Name';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."EVAL_AGENT_EMAIL" IS 'Designated Evaluation Agent Email';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."EVAL_AGENT_PHONE" IS 'Designated Evaluation Agent Telephone';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."SUPRANATIONAL" IS 'Supranational Status';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."US_PERSON" IS 'U.S. Person';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."EMIR_RECON_EXEMPT" IS 'EMIR Portfolio Recon Exemption';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."BROKER" IS 'Broker';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."ELECTRONIC_PLATFORM" IS 'Electronic Platform';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."PNC_BU_ID" IS 'BU-ID';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CLR_EX_END_USER_EXCEPTION" IS 'Clearing exemption - End-user exception';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CLR_EX_INT_AFF_EXEMPTION" IS 'Clearing exemption -  Inter-affiliate exemption';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CLR_EX_SMALL_BK_EXEMPTION" IS 'Clearing exemption - Small bank exemption';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CLR_EX_COOP_EXEMPTION" IS 'Clearing exemption - Cooperative exemption';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CLR_EX_NO_ACT_LETTER" IS 'Clearing exemption - No-action letter';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CLR_EX_OTHER_EXCEPTIONS" IS 'Clearing exemption - Other exceptions';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."FED_ENTITY_INDICATOR" IS 'Federal entity indicator';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."PLATFORM_ID_TYPE" IS 'Platform identifier - Platform Type';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."MIC" IS 'Platform identifier - MIC (ISO code)';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."AFF_CPTY_MARG_CAP_INDICATOR" IS 'Affiliated Counterparty for Margin & Capital indicator';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CPTY_ID_SOURCE_NAT_PERS_IND" IS 'Counterparty identifier source - Natural person indicator';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CPTY_ID_SOURCE_PRIV_LAW_IDENT" IS 'Counterparty identifier source - Privacy Law Identifier';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."SFTR_UTI_SCENARIO" IS 'SFTR Field';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CPTY_ID_SRC_PRIVLAW_ID_BOI" IS 'Counterparty identifier source - Privacy Law Identifier Bank of Israel';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."BNC_ID" IS 'Code BNC_ID';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."FUND_MANAGER" IS 'ID Smartco (Agent)';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."TICKER" IS 'Ticker Code';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."NRA_TAX_POOL" IS 'NRA tax pool';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CORPORATE_SECTOR_FC" IS 'Allows a CP which is an FC to communicate to NBCGF or NBC, information relating to its company activities, as required pursuant to field 6 or field 12 (as applicable) of Table 1 of the Annexes to Commission Delegated Regulation (EU) 2022/1855';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CORPORATE_SECTOR_NFC" IS 'Allows a CP which is an NFC, to communicate to NBCGF or NBC information relating to its company activities, as required pursuant to field 6 or field 12 (as applicable) of Table 1 of the Annexes to Commission Delegated Regulation (EU) 2022/1855';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CLEARING_THRESHOLD_EXEEDED" IS 'Information whether the CP is above the clearing threshold referred to in Article 4(a)(3) or 10(3) of Regulation (EU) No 648/2012.';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."UK_VS_EU_BASED" IS 'Is the CP domiciled within the EU or within the UK.';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."OPT_OUT_EMIR_REPORTING" IS 'An NFC- CP may opt out of the new mandatory reporting regime and continue to report on its own behalf. If it chooses to do so, it must inform NBCGF of its decision prior to transacting.';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."EMIR_PORTFOLIO_RECON_ELECTIONS" IS 'EMIR portfolio reconciliation modalities';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."ESMA_INTRA_CLRNG_EXEMPTION" IS 'Intra-group transactions are exempted from central clearing under certain conditions.';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CLIENT_MANAGEMENT" IS 'Client management (list : RMS FM, RMS CCM, RMS P&C, FICC, empty)';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CLIENT_PLATFORM" IS 'Client Platform (list (Yes, No)';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."EMIR_EU_ONBOARDING" IS 'Emir onboarding status';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."EMIR_REPORTING_OBLIGATION" IS 'Emir reporting obligation';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CBCR_DERIVATIVE_PARTY_TYPE" IS '	CBCR Derivative Party Type';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CBCR_WAIVER" IS 'CBCR Waiver';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CBCR_VERIFICATION_TYPE" IS 'CBCR Verification Type';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."CBCR_NAV" IS 'CBCR Net Asset Value';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."HKMA_PROF_INVESTORS_TYPE" IS 'Hkma professional investors type';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."HKMA_ONBOARDING_STATUS" IS 'Hkma onboarding status';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."US_CP_SCORE" IS 'A computed score indicating whether each counterparty requires PTMMM.';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."INVESTMENT_MANAGER" IS 'Investment Manager Role';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."EXECUTION_AGENT" IS 'Standard id assigned to the execution agent related to the counterpart, if applicable. ';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."SEF_ONLY" IS 'Flag to identify SEF Only funds';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."HKMA_CORP_SECTOR" IS 'HKMA corporate sector';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_COUNTERPARTY"."HKMA_CLASSIFICATION" IS 'HKMA classification';
  GRANT SELECT ON "SDH"."TB_SMARTCO_COUNTERPARTY" TO "TMF_SERVICES" WITH GRANT OPTION;
--------------------------------------------------------
--  Constraints for Table TB_SMARTCO_COUNTERPARTY
--------------------------------------------------------

  ALTER TABLE "SDH"."TB_SMARTCO_COUNTERPARTY" MODIFY ("SYS_CREAT_DTMS" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_COUNTERPARTY" MODIFY ("SYS_CREAT_PROCSS_USR_ID" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_COUNTERPARTY" MODIFY ("SYS_PARTITION_ID" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_COUNTERPARTY" MODIFY ("RPY_VALUE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_COUNTERPARTY" MODIFY ("RPY_VALUE_TM" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_COUNTERPARTY" MODIFY ("RPY_LOAD_TIMELN_VAL" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_COUNTERPARTY" MODIFY ("DIV_NAME" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_COUNTERPARTY" MODIFY ("SYS_NAME" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_COUNTERPARTY" MODIFY ("SIT_CODE" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_COUNTERPARTY" MODIFY ("RPY_SID" NOT NULL ENABLE);
