--------------------------------------------------------
--  File created - Saturday-February-21-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TB_SMARTCO_ISSUER
--------------------------------------------------------

  CREATE TABLE "SDH"."TB_SMARTCO_ISSUER" 
   (	"SYS_CREAT_DTMS" DATE DEFAULT SYSDATE, 
	"SYS_CREAT_PROCSS_USR_ID" VARCHAR2(100 BYTE), 
	"SYS_UPDT_DTMS" DATE, 
	"SYS_UPDT_PROCSS_USR_ID" VARCHAR2(100 BYTE), 
	"SYS_PARTITION_ID" VARCHAR2(30 BYTE), 
	"RPY_VALUE_DATE" DATE, 
	"RPY_VALUE_TM" VARCHAR2(8 BYTE), 
	"RPY_LOAD_TIMELN_VAL" VARCHAR2(10 BYTE), 
	"DIV_NAME" VARCHAR2(30 BYTE), 
	"SYS_NAME" VARCHAR2(30 BYTE), 
	"SIT_CODE" VARCHAR2(10 BYTE), 
	"RPY_SID" NUMBER(38,0), 
	"REQUEST_DATE" DATE, 
	"ISSUER_UNIQUE_KEY" VARCHAR2(50 BYTE), 
	"ISSUER_ID_BB_COMPANY" VARCHAR2(50 BYTE), 
	"ISSUER_NAME" VARCHAR2(255 BYTE), 
	"RISK_ENTITY_SHORT_NAME" VARCHAR2(255 BYTE), 
	"ISSUER_MIDAS_ID" VARCHAR2(50 BYTE), 
	"LEGAL_ENTITY_IDENTIFIER" VARCHAR2(255 BYTE), 
	"ULTIMATE_PARENT_COMPANY_NAME" VARCHAR2(50 BYTE), 
	"BICS_INDUSTRY_SECTOR" VARCHAR2(50 BYTE), 
	"BICS_INDUSTRY_GROUP" VARCHAR2(50 BYTE), 
	"BICS_INDUSTRY_SUBGROUP" VARCHAR2(50 BYTE), 
	"GICS_SECTOR" VARCHAR2(50 BYTE), 
	"GICS_INDUSTRY_GROUP" VARCHAR2(255 BYTE), 
	"GICS_INDUSTRY" VARCHAR2(255 BYTE), 
	"GICS_SUB_INDUSTRY" VARCHAR2(255 BYTE), 
	"NAICS_EDITION_CODE" VARCHAR2(50 BYTE), 
	"NAICS" VARCHAR2(50 BYTE), 
	"NAICS_IND_WEIGHT" VARCHAR2(255 BYTE), 
	"ISSUER_INCORPORATION_COUNTRY" VARCHAR2(50 BYTE), 
	"ISSUER_DOMICILE_COUNTRY" VARCHAR2(50 BYTE), 
	"ISSUER_DOMICILE_ADDRESS_NUMBER" VARCHAR2(255 BYTE), 
	"ISSUER_RISK_COUNTRY" VARCHAR2(50 BYTE), 
	"ULTIMATE_PARENT_INC_CNTRY" VARCHAR2(50 BYTE), 
	"ULTIMATE_PARENT_DOMICILE_CNTRY" VARCHAR2(50 BYTE), 
	"ULTIMATE_PARENT_RISK_COUNTRY" VARCHAR2(255 BYTE), 
	"MDB_HIGH_RATED" VARCHAR2(255 BYTE), 
	"RTG_MDY_ISSUER" VARCHAR2(50 BYTE), 
	"RTG_MDY_ISSUER_EFFECTIVE_DT" DATE, 
	"RTG_MDY_ISSUER_REFRESH_DT" DATE, 
	"RTG_MDY_SEN_UNSECURED_DEBT" VARCHAR2(50 BYTE), 
	"RTG_MDY_SEN_UNSEC_DEBT_EFF_DT" DATE, 
	"RTG_MDY_SEN_UNSEC_DEBT_REF_DT" DATE, 
	"RTG_MDY_SEN_SUB_DEBT" VARCHAR2(50 BYTE), 
	"RTG_MDY_SEN_SUB_DEBT_EFF_DT" DATE, 
	"RTG_MDY_SEN_SUB_DEBT_REF_DT" DATE, 
	"RTG_MDY_LT_FC_DEBT" VARCHAR2(50 BYTE), 
	"RTG_MDY_LT_FC_DEBT_EFF_DT" DATE, 
	"RTG_MDY_LT_FC_DEBT_REF_DT" DATE, 
	"RTG_MDY_LT_LC_DEBT" VARCHAR2(50 BYTE), 
	"RTG_MDY_LT_LC_DEBT_EFF_DT" DATE, 
	"RTG_MDY_LT_LC_DEBT_REF_DT" DATE, 
	"RTG_MOODY_LONG_TERM" VARCHAR2(50 BYTE), 
	"RTG_MOODY_LONG_TERM_EFF_DT" DATE, 
	"RTG_MOODY_LONG_TERM_REF_DT" DATE, 
	"RTG_MDY_SHORT_TERM_DEBT" VARCHAR2(50 BYTE), 
	"RTG_MDY_SHORT_TERM_DEBT_EFF_DT" DATE, 
	"RTG_MDY_SHORT_TERM_DEBT_REF_DT" DATE, 
	"RTG_FITCH_LT_FC_DEBT" VARCHAR2(50 BYTE), 
	"RTG_FITCH_LT_FC_DEBT_EFF_DT" DATE, 
	"RTG_FITCH_LT_FC_DEBT_REF_DT" DATE, 
	"RTG_FITCH_LT_LC_DEBT" VARCHAR2(50 BYTE), 
	"RTG_FITCH_LT_LC_DEBT_EFF_DT" DATE, 
	"RTG_FITCH_LT_LC_DEBT_REF_DT" DATE, 
	"RTG_FITCH_LONG_TERM" VARCHAR2(50 BYTE), 
	"RTG_FITCH_LONG_TERM_EFF_DT" DATE, 
	"RTG_FITCH_LONG_TERM_REF_DT" DATE, 
	"RTG_FITCH_SHORT_TERM" VARCHAR2(50 BYTE), 
	"RTG_FITCH_SHORT_TERM_EFF_DT" DATE, 
	"RTG_FITCH_SHORT_TERM_REF_DT" DATE, 
	"RTG_FITCH_SEN_UNSECURED" VARCHAR2(50 BYTE), 
	"RTG_FITCH_SEN_UNSEC_EFF_DT" DATE, 
	"RTG_FITCH_SEN_UNSEC_REF_DT" DATE, 
	"RTG_DBRS_LT_ISSUER_RATING" VARCHAR2(50 BYTE), 
	"RTG_DBRS_LT_ISSUER_RTG_EFF_DT" DATE, 
	"RTG_DBRS_LT_ISSUER_RTG_REF_DT" DATE, 
	"RTG_DBRS_SENIOR_SECURED" VARCHAR2(50 BYTE), 
	"RTG_DBRS_SENIOR_SEC_EFF_DT" DATE, 
	"RTG_DBRS_SENIOR_SEC_REF_DT" DATE, 
	"RTG_DBRS_SENIOR_UNSECURED" VARCHAR2(50 BYTE), 
	"RTG_DBRS_SENIOR_UNSEC_EFF_DT" DATE, 
	"RTG_DBRS_SENIOR_UNSEC_REF_DT" DATE, 
	"RTG_DBRS_ST_ISSUER_RATING" VARCHAR2(50 BYTE), 
	"RTG_DBRS_ST_ISSUER_RTG_EFF_DT" DATE, 
	"RTG_DBRS_ST_ISSUER_RTG_REF_DT" DATE, 
	"RTG_DBRS_ST" VARCHAR2(50 BYTE), 
	"RTG_DBRS_ST_EFFECTIVE_DT" DATE, 
	"RTG_DBRS_ST_REFRESH_DT" DATE, 
	"RTG_DBRS_LT_BANK_DEPOSITS" VARCHAR2(50 BYTE), 
	"RTG_DBRS_LT_BANK_DEP_EFF_DT" DATE, 
	"RTG_DBRS_LT_BANK_DEP_REF_DT" DATE, 
	"RTG_SP_LT_LI_CREDIT" VARCHAR2(50 BYTE), 
	"RTG_SP_LT_LI_CRED_EFF_DT" DATE, 
	"RTG_SP_LT_LI_CRED_REF_DT" DATE, 
	"RTG_SP_LT_FI_CREDIT" VARCHAR2(50 BYTE), 
	"RTG_SP_LT_FI_CRE_EFF_DT" DATE, 
	"RTG_SP_LT_FI_CRE_REF_DT" DATE, 
	"RTG_SP_ST_LI_CREDIT" VARCHAR2(50 BYTE), 
	"RTG_SP_ST_LI_CRE_EFF_DT" DATE, 
	"RTG_SP_ST_LI_CRE_REF_DT" DATE, 
	"RTG_SP_ST_FI_CREDIT" VARCHAR2(50 BYTE), 
	"RTG_SP_ST_FI_CRED_EFF_DT" DATE, 
	"RTG_SP_ST_FI_CRED_REF_DT" DATE, 
	"RTG_SP_LT_LC_DEBT" VARCHAR2(50 BYTE), 
	"RTG_SP_LT_LC_DEBT_EFFECTIVE_DT" DATE, 
	"RTG_SP_LT_LC_DEBT_REFRESH_DT" DATE, 
	"RTG_SP_LT_FC_DEBT" VARCHAR2(50 BYTE), 
	"RTG_SP_LT_FC_DEBT_EFFECTIVE_DT" DATE, 
	"RTG_SP_LT_FC_DEBT_REFRESH_DT" DATE, 
	"RTG_SP_ST_LC_DEBT" VARCHAR2(50 BYTE), 
	"RTG_SP_ST_LC_DEBT_EFFECTIVE_DT" DATE, 
	"RTG_SP_ST_LC_DEBT_REFRESH_DT" DATE, 
	"RTG_SP_ST_FC_DEBT" VARCHAR2(50 BYTE), 
	"RTG_SP_ST_FC_DEBT_EFFECTIVE_DT" DATE, 
	"RTG_SP_ST_FC_DEBT_REFRESH_DT" DATE, 
	"PROVINCE_NAME" VARCHAR2(255 BYTE), 
	"PROVINCE_STATE_CODE" VARCHAR2(50 BYTE), 
	"PROVINCE_BICS_INDUSTRY_SUBGRP" VARCHAR2(50 BYTE), 
	"RTG_SP_PROVINCE" VARCHAR2(50 BYTE), 
	"RTG_SP_PROVINCE_EFFECTIVE_DT" DATE, 
	"RTG_SP_PROVINCE_REFRESH_DT" DATE, 
	"RTG_SP_PROVINCE_COTE_MIN1" VARCHAR2(50 BYTE), 
	"RTG_SP_PROV_COTE_MIN1_EFF_DT" DATE, 
	"RTG_SP_PRO_COTEM_MIN1_REF_DT" DATE, 
	"ID_BB_PARENT_COMPANY" VARCHAR2(50 BYTE), 
	"PARENT_COMPANY_INC_CNTRY" VARCHAR2(50 BYTE), 
	"PARENT_COMPANY_DOMICILE_CNTRY" VARCHAR2(50 BYTE), 
	"PARENT_COMPANY_RISK_COUNTRY" VARCHAR2(50 BYTE), 
	"ISSUER_DOMICILE_STATE" VARCHAR2(50 BYTE), 
	"ISSUER_DOMICILE_CITY" VARCHAR2(255 BYTE), 
	"ISSUER_INCORPORATION_STATE" VARCHAR2(50 BYTE), 
	"RTG_MDY_BANK_LOAN_DEBT" VARCHAR2(50 BYTE), 
	"RTG_MDY_BANK_LOAN_DEBT_EFF_DT" DATE, 
	"RTG_MDY_BANK_LOAN_DEBT_REF_DT" DATE, 
	"ID_BB_PROVINCE" VARCHAR2(50 BYTE), 
	"RTG_MDY_SUBORDINATED_DEBT" VARCHAR2(50 BYTE), 
	"RTG_MDY_SUBORD_DEBT_EFF_DT" DATE, 
	"RTG_MDY_SUBORD_DEBT_REF_DT" DATE, 
	"RTG_SP_SUBORDINATED_DEBT" VARCHAR2(255 BYTE), 
	"RTG_SP_SUBORD_DEBT_EFF_DT" DATE, 
	"RTG_SP_SUBORD_DEBT_REF_DT" DATE, 
	"RTG_FITCH_SUBORDINATED_DEBT" VARCHAR2(50 BYTE), 
	"RTG_FITCH_SUBORD_DEBT_EFF_DT" DATE, 
	"RTG_FITCH_SUBORD_DEBT_REF_DT" DATE, 
	"RTG_DBRS_SUBORDINATE" VARCHAR2(50 BYTE), 
	"RTG_DBRS_SUBORD_EFF_DT" DATE, 
	"RTG_DBRS_SUBORD_REF_DT" DATE, 
	"DEFAULT_RTG" VARCHAR2(50 BYTE), 
	"DEFAULT_RTG_EFF_DATE" DATE, 
	"DEFAULT_RTG_REASON_CODE" VARCHAR2(255 BYTE), 
	"BICS_INDUSTRY_SECTOR_CODE" VARCHAR2(50 BYTE), 
	"BICS_INDUSTRY_GROUP_CODE" VARCHAR2(50 BYTE), 
	"BICS_INDUSTRY_SUBGROUP_CODE" VARCHAR2(50 BYTE), 
	"SSA_FLAG" VARCHAR2(50 BYTE), 
	"DEFAULT_RATING_VALIDATION_DATE" DATE, 
	"STANDARD_ID" NUMBER(38,16), 
	"ULTIMATE_PARENT_STDID" NUMBER(38,16), 
	"BB_PARENT_CO_STDID" NUMBER(38,16), 
	"REF_SECTOR" VARCHAR2(255 BYTE), 
	"MARKETCAP_CLASSIFICATION" VARCHAR2(50 BYTE), 
	"NAICS_SECTOR" VARCHAR2(255 BYTE), 
	"NAICS_SUB_SECTOR" VARCHAR2(255 BYTE), 
	"NAICS_INDUSTRY_GROUP" VARCHAR2(255 BYTE), 
	"NAICS_INDUSTRY" VARCHAR2(255 BYTE), 
	"NAICS_NATIONAL_INDUSTRY" VARCHAR2(255 BYTE), 
	"REF_INDUSTRY_GROUP" VARCHAR2(255 BYTE), 
	"REF_INDUSTRY" VARCHAR2(255 BYTE), 
	"REF_SUB_INDUSTRY" VARCHAR2(255 BYTE), 
	"ID_RED_ENTITY_CODE" VARCHAR2(255 BYTE), 
	"FRTB_RATING" VARCHAR2(255 BYTE), 
	"MARKETCAP_FRTB_ESA" VARCHAR2(255 BYTE), 
	"MARKETCAP_FRTB_OSFI" VARCHAR2(255 BYTE), 
	"CENTRAL_INDEX_KEY_NUMBER" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 ROW STORE COMPRESS ADVANCED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
  PARTITION BY LIST ("RPY_VALUE_DATE") 
  SUBPARTITION BY LIST ("SYS_PARTITION_ID") 
 (PARTITION "P_20251030"  VALUES (TO_DATE(' 2025-10-30 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202510300101045N"  VALUES ('202510300101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251031"  VALUES (TO_DATE(' 2025-10-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202510310101045N"  VALUES ('202510310101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251103"  VALUES (TO_DATE(' 2025-11-03 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511030101045N"  VALUES ('202511030101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251104"  VALUES (TO_DATE(' 2025-11-04 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511040101045N"  VALUES ('202511040101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251105"  VALUES (TO_DATE(' 2025-11-05 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511050101045N"  VALUES ('202511050101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251106"  VALUES (TO_DATE(' 2025-11-06 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511060101045N"  VALUES ('202511060101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251107"  VALUES (TO_DATE(' 2025-11-07 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511070101045N"  VALUES ('202511070101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251110"  VALUES (TO_DATE(' 2025-11-10 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511100101045N"  VALUES ('202511100101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251111"  VALUES (TO_DATE(' 2025-11-11 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511110101045N"  VALUES ('202511110101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251112"  VALUES (TO_DATE(' 2025-11-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511120101045N"  VALUES ('202511120101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251113"  VALUES (TO_DATE(' 2025-11-13 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511130101045N"  VALUES ('202511130101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251114"  VALUES (TO_DATE(' 2025-11-14 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511140101045N"  VALUES ('202511140101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251117"  VALUES (TO_DATE(' 2025-11-17 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511170101045N"  VALUES ('202511170101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251118"  VALUES (TO_DATE(' 2025-11-18 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511180101045N"  VALUES ('202511180101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251119"  VALUES (TO_DATE(' 2025-11-19 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511190101045N"  VALUES ('202511190101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251120"  VALUES (TO_DATE(' 2025-11-20 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511200101045N"  VALUES ('202511200101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251121"  VALUES (TO_DATE(' 2025-11-21 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511210101045N"  VALUES ('202511210101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251124"  VALUES (TO_DATE(' 2025-11-24 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511240101045N"  VALUES ('202511240101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251125"  VALUES (TO_DATE(' 2025-11-25 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511250101045N"  VALUES ('202511250101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251126"  VALUES (TO_DATE(' 2025-11-26 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511260101045N"  VALUES ('202511260101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251127"  VALUES (TO_DATE(' 2025-11-27 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511270101045N"  VALUES ('202511270101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251128"  VALUES (TO_DATE(' 2025-11-28 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511280101045N"  VALUES ('202511280101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251201"  VALUES (TO_DATE(' 2025-12-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512010101045N"  VALUES ('202512010101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251202"  VALUES (TO_DATE(' 2025-12-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512020101045N"  VALUES ('202512020101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251203"  VALUES (TO_DATE(' 2025-12-03 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512030101045N"  VALUES ('202512030101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251204"  VALUES (TO_DATE(' 2025-12-04 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512040101045N"  VALUES ('202512040101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251205"  VALUES (TO_DATE(' 2025-12-05 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512050101045N"  VALUES ('202512050101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251208"  VALUES (TO_DATE(' 2025-12-08 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512080101045N"  VALUES ('202512080101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251209"  VALUES (TO_DATE(' 2025-12-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512090101045N"  VALUES ('202512090101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251210"  VALUES (TO_DATE(' 2025-12-10 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512100101045N"  VALUES ('202512100101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251211"  VALUES (TO_DATE(' 2025-12-11 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512110101045N"  VALUES ('202512110101045N') SEGMENT CREATION IMMEDIATE 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251212"  VALUES (TO_DATE(' 2025-12-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512120101045N"  VALUES ('202512120101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251215"  VALUES (TO_DATE(' 2025-12-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512150101045N"  VALUES ('202512150101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251216"  VALUES (TO_DATE(' 2025-12-16 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512160101045N"  VALUES ('202512160101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251217"  VALUES (TO_DATE(' 2025-12-17 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512170101045N"  VALUES ('202512170101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251218"  VALUES (TO_DATE(' 2025-12-18 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512180101045N"  VALUES ('202512180101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251219"  VALUES (TO_DATE(' 2025-12-19 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512190101045N"  VALUES ('202512190101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251222"  VALUES (TO_DATE(' 2025-12-22 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512220101045N"  VALUES ('202512220101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251223"  VALUES (TO_DATE(' 2025-12-23 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512230101045N"  VALUES ('202512230101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251224"  VALUES (TO_DATE(' 2025-12-24 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512240101045N"  VALUES ('202512240101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251226"  VALUES (TO_DATE(' 2025-12-26 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512260101045N"  VALUES ('202512260101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251229"  VALUES (TO_DATE(' 2025-12-29 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512290101045N"  VALUES ('202512290101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251230"  VALUES (TO_DATE(' 2025-12-30 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512300101045N"  VALUES ('202512300101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251231"  VALUES (TO_DATE(' 2025-12-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512310101045N"  VALUES ('202512310101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260102"  VALUES (TO_DATE(' 2026-01-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601020101045N"  VALUES ('202601020101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260105"  VALUES (TO_DATE(' 2026-01-05 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601050101045N"  VALUES ('202601050101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260106"  VALUES (TO_DATE(' 2026-01-06 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601060101045N"  VALUES ('202601060101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260107"  VALUES (TO_DATE(' 2026-01-07 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601070101045N"  VALUES ('202601070101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260108"  VALUES (TO_DATE(' 2026-01-08 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601080101045N"  VALUES ('202601080101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260109"  VALUES (TO_DATE(' 2026-01-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601090101045N"  VALUES ('202601090101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260112"  VALUES (TO_DATE(' 2026-01-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601120101045N"  VALUES ('202601120101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260113"  VALUES (TO_DATE(' 2026-01-13 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601130101045N"  VALUES ('202601130101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260114"  VALUES (TO_DATE(' 2026-01-14 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601140101045N"  VALUES ('202601140101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260115"  VALUES (TO_DATE(' 2026-01-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601150101045N"  VALUES ('202601150101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260116"  VALUES (TO_DATE(' 2026-01-16 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601160101045N"  VALUES ('202601160101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260119"  VALUES (TO_DATE(' 2026-01-19 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601190101045N"  VALUES ('202601190101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260120"  VALUES (TO_DATE(' 2026-01-20 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601200101045N"  VALUES ('202601200101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260121"  VALUES (TO_DATE(' 2026-01-21 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601210101045N"  VALUES ('202601210101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260122"  VALUES (TO_DATE(' 2026-01-22 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601220101045N"  VALUES ('202601220101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260123"  VALUES (TO_DATE(' 2026-01-23 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601230101045N"  VALUES ('202601230101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260126"  VALUES (TO_DATE(' 2026-01-26 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601260101045N"  VALUES ('202601260101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260127"  VALUES (TO_DATE(' 2026-01-27 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601270101045N"  VALUES ('202601270101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260128"  VALUES (TO_DATE(' 2026-01-28 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601280101045N"  VALUES ('202601280101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260129"  VALUES (TO_DATE(' 2026-01-29 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601290101045N"  VALUES ('202601290101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260130"  VALUES (TO_DATE(' 2026-01-30 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601300101045N"  VALUES ('202601300101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260202"  VALUES (TO_DATE(' 2026-02-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202602020101045N"  VALUES ('202602020101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) ) ;

   COMMENT ON COLUMN "SDH"."TB_SMARTCO_ISSUER"."REF_SECTOR" IS 'Indicate the agent reference sector';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_ISSUER"."MARKETCAP_CLASSIFICATION" IS 'Market cap classification.';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_ISSUER"."NAICS_SECTOR" IS 'Naics sector';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_ISSUER"."NAICS_SUB_SECTOR" IS 'Naics sub sector';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_ISSUER"."NAICS_INDUSTRY_GROUP" IS 'Naics Industry group';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_ISSUER"."NAICS_INDUSTRY" IS 'Naics industry';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_ISSUER"."NAICS_NATIONAL_INDUSTRY" IS 'Naics National Industry';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_ISSUER"."REF_INDUSTRY_GROUP" IS 'Reference Industry group';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_ISSUER"."REF_INDUSTRY" IS 'Reference Industry';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_ISSUER"."REF_SUB_INDUSTRY" IS 'Reference Sub Industry ';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_ISSUER"."ID_RED_ENTITY_CODE" IS 'Red Entity code';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_ISSUER"."FRTB_RATING" IS 'Reference Rating for FRTB';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_ISSUER"."MARKETCAP_FRTB_ESA" IS 'Agent Classif FRTB ESA- Agent classif list UMR';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_ISSUER"."MARKETCAP_FRTB_OSFI" IS 'Agent Classif FRTB OSFI-Agent classif list UMR';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_ISSUER"."CENTRAL_INDEX_KEY_NUMBER" IS 'CENTRAL_INDEX_KEY_NUMBER';
  GRANT SELECT ON "SDH"."TB_SMARTCO_ISSUER" TO "TMF_SERVICES" WITH GRANT OPTION;
--------------------------------------------------------
--  Constraints for Table TB_SMARTCO_ISSUER
--------------------------------------------------------

  ALTER TABLE "SDH"."TB_SMARTCO_ISSUER" MODIFY ("SYS_CREAT_DTMS" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_ISSUER" MODIFY ("SYS_CREAT_PROCSS_USR_ID" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_ISSUER" MODIFY ("SYS_PARTITION_ID" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_ISSUER" MODIFY ("RPY_VALUE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_ISSUER" MODIFY ("RPY_VALUE_TM" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_ISSUER" MODIFY ("RPY_LOAD_TIMELN_VAL" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_ISSUER" MODIFY ("DIV_NAME" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_ISSUER" MODIFY ("SYS_NAME" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_ISSUER" MODIFY ("SIT_CODE" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_ISSUER" MODIFY ("RPY_SID" NOT NULL ENABLE);
