--------------------------------------------------------
--  File created - Friday-March-13-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TB_SMARTCO_INSTRUMENTDATA
--------------------------------------------------------

  CREATE TABLE "SDH"."TB_SMARTCO_INSTRUMENTDATA" 
   (	"SYS_CREAT_DTMS" DATE DEFAULT SYSDATE, 
	"SYS_CREAT_PROCSS_USR_ID" VARCHAR2(100 BYTE), 
	"SYS_UPDT_DTMS" DATE, 
	"SYS_UPDT_PROCSS_USR_ID" VARCHAR2(100 BYTE), 
	"SYS_PARTITION_ID" VARCHAR2(30 BYTE), 
	"RIM_VALUE_DATE" DATE, 
	"RIM_VALUE_TM" VARCHAR2(8 BYTE), 
	"RIM_LOAD_TIMELN_VAL" VARCHAR2(10 BYTE), 
	"DIV_NAME" VARCHAR2(30 BYTE), 
	"SYS_NAME" VARCHAR2(30 BYTE), 
	"SIT_CODE" VARCHAR2(10 BYTE), 
	"RIM_SID" NUMBER(38,16), 
	"REQUEST_DATE" DATE, 
	"INSTRUMENT_UNIQUE_KEY" VARCHAR2(50 BYTE), 
	"EFFECTIVE_DT" DATE, 
	"AMT_OUTSTANDING" NUMBER(38,16), 
	"SH_OUT" NUMBER(38,16), 
	"NXT_REDEMP_DT" DATE, 
	"NXT_STEPUP_DT" DATE, 
	"PX_VOLUME" NUMBER(38,16), 
	"VOLUME_AVG_10D" NUMBER(38,16), 
	"VOLUME_AVG_30D" NUMBER(38,16), 
	"VOLUME_AVG_90D" NUMBER(38,16), 
	"PX_BID" NUMBER(38,16), 
	"PX_ASK" NUMBER(38,16), 
	"QUOTE_FINAL" NUMBER(38,16), 
	"RISK_MID" NUMBER(38,16), 
	"DELTA" NUMBER(38,16), 
	"GAMMA" NUMBER(38,16), 
	"VEGA" NUMBER(38,16), 
	"THETA" NUMBER(38,16), 
	"RHO" NUMBER(38,16), 
	"UNDL_PX" NUMBER(38,16), 
	"CV_CNVS_RATIO" NUMBER(38,16), 
	"WRT_SH_PER" NUMBER(38,16), 
	"FUT_VAL_PT" VARCHAR2(50 BYTE), 
	"FUT_CONT_SIZE" NUMBER(38,16), 
	"FUT_CTD_MTY" DATE, 
	"FUT_CTD_CPN" NUMBER(38,16), 
	"FUT_CTD_DAYCOUNT" VARCHAR2(50 BYTE), 
	"FUT_CTD_FREQ" VARCHAR2(50 BYTE), 
	"STEPUP_CPN" NUMBER(38,16), 
	"NXT_PUT_PX" NUMBER(38,16), 
	"NXT_PUT_DT" DATE, 
	"NXT_CALL_PX" NUMBER(38,16), 
	"NXT_REFIX_DT" DATE, 
	"NXT_CPN_DT" DATE, 
	"CPN" NUMBER(38,16), 
	"INT_ACC" NUMBER(38,16), 
	"VOLUME_AVG_180D" NUMBER(38,16), 
	"PX_LAST" NUMBER(38,16), 
	"TRADE_STATUS" VARCHAR2(50 BYTE), 
	"MARKET_STATUS" VARCHAR2(50 BYTE), 
	"WORKOUT_DT_MID" DATE, 
	"PX_LAST_DT" DATE, 
	"MTG_BAL_PRIOR_MTY_1M" NUMBER(38,16), 
	"MTG_BAL_PRIOR_MTY_2M" NUMBER(38,16), 
	"MTG_BAL_PRIOR_MTY_3M" NUMBER(38,16), 
	"MTG_BAL_PRIOR_MTY_4M" NUMBER(38,16), 
	"MTG_BAL_PRIOR_MTY_5M" NUMBER(38,16), 
	"MTG_WACPN" NUMBER(38,16), 
	"MTG_WAMAT" NUMBER(38,16), 
	"CHEAPEST_TO_DELIVER" VARCHAR2(50 BYTE), 
	"CONVERSION_FACTOR" NUMBER(38,16), 
	"LAST_REFIX_DT" DATE, 
	"INT_ACC_DT" DATE, 
	"MTG_WAL" NUMBER(38,16), 
	"DVD_EX_DT" DATE, 
	"DVD_FREQ" VARCHAR2(50 BYTE), 
	"DVD_CRNCY" VARCHAR2(50 BYTE), 
	"DVD_SH_LAST" NUMBER(38,16), 
	"DVD_TYP_LAST" VARCHAR2(50 BYTE), 
	"EQY_DVD_YLD_IND" NUMBER(38,16), 
	"POOL_REDEMPTION_FACTOR" NUMBER(38,16), 
	"TRSY_SPREAD" NUMBER(38,16), 
	"CUR_MKT_CAP" NUMBER(38,16), 
	"BVAL_MID_SCORE" VARCHAR2(50 BYTE), 
	"FUT_FAIR_VAL" NUMBER(38,16), 
	"STANDARD_ID" NUMBER(38,16), 
	"CHEAPEST_STDID" NUMBER(38,16), 
	"REF_SEC_UNIQUE_KEY" VARCHAR2(100 BYTE), 
	"FACTOR" NUMBER(38,16), 
	"REF_CURR" VARCHAR2(3 BYTE), 
	"REF_SEC_STD_ID" VARCHAR2(100 BYTE), 
	"DUR_ADJ_MID" NUMBER(38,16), 
	"YLD_CNV_MID" NUMBER(38,16), 
	"CURRENT_TRR_1MO" NUMBER(38,16), 
	"CURRENT_TRR_3MO" NUMBER(38,16), 
	"CURRENT_TRR_YTD" NUMBER(38,16), 
	"CURRENT_TRR_1YR" NUMBER(38,16), 
	"CURRENT_ANN_TRR_3YR" NUMBER(38,16), 
	"CURRENT_ANN_TRR_5YR" NUMBER(38,16), 
	"VOLATILITY_360D" NUMBER(38,16), 
	"VOLATILITY_360D_CALC" NUMBER(38,16), 
	"REF_WEALTH" NUMBER(38,16), 
	"ID_ISIN" VARCHAR2(100 BYTE), 
	"VOLUME_AVG_5D" NUMBER(38,16), 
	"PX_YEST_CLOSE" NUMBER(38,16), 
	"CNTRY_ISSUE_ISO" VARCHAR2(2 BYTE), 
	"AGG_AVG_VOL_90D" NUMBER(38,16), 
	"YLD_FINAL" NUMBER(38,16), 
	"YLD_ASK" NUMBER(38,16), 
	"YLD_BID" NUMBER(38,16), 
	"AGG_AVG_VOL_180D" NUMBER(38,16), 
	"EXCHANGE" VARCHAR2(50 BYTE), 
	"CURRENCY" VARCHAR2(100 BYTE), 
	"COUNTRY" VARCHAR2(100 BYTE), 
	"FLAG_PRIMARY_MARKET" VARCHAR2(50 BYTE), 
	"AGG_AVG_VOL_30D" NUMBER(38,16), 
	"BETA" NUMBER(38,16), 
	"CHG_PCT_1M" NUMBER(38,16), 
	"CHG_PCT_3M" NUMBER(38,16), 
	"CHG_PCT_6M" NUMBER(38,16), 
	"CHG_PCT_1YR" NUMBER(38,16), 
	"CHG_PCT_MTD" NUMBER(38,16), 
	"CHG_PCT_QTD" NUMBER(38,16), 
	"CHG_PCT_YTD" NUMBER(38,16), 
	"CV_MODEL_VEGA" NUMBER(38,16), 
	"CV_MODEL_DELTA_V" NUMBER(38,16), 
	"CV_MODEL_GAMMA_V" NUMBER(38,16), 
	"FUT_CNV_RISK_FRSK" NUMBER(38,16), 
	"FUT_PX_VAL_BP" NUMBER(38,16), 
	"DELTA_MID" NUMBER(38,16), 
	"GAMMA_MID" NUMBER(38,16), 
	"VEGA_MID" NUMBER(38,16), 
	"INTEREST_RATE_SENSITIVITY" NUMBER(38,16), 
	"CREDIT_SENSITIVITY" NUMBER(38,16), 
	"DVD_DECLARED_DT" DATE, 
	"DVD_RECORD_DT" DATE, 
	"DVD_PAY_DT" DATE, 
	"LAST_DPS_GROSS" NUMBER(38,16), 
	"NET_ASSET" NUMBER(38,16), 
	"NAV_CRNCY" VARCHAR2(255 BYTE), 
	"INTRINSIC_VALUE" NUMBER(38,16), 
	"TOT_RETURN_INDEX_NET_DVDS" NUMBER(38,16), 
	"AVG_YIELD" NUMBER(38,16), 
	"PRICE_INDEX" NUMBER(38,16), 
	"MACAULAY_DURATION" NUMBER(38,16), 
	"MODIFIED_DURATION" NUMBER(38,16), 
	"MONEY_DURATION" NUMBER(38,16), 
	"AVG_COUPON" NUMBER(38,16), 
	"AVG_MATURITY" NUMBER(38,16), 
	"FUT_AGGTE_OPEN_INT" NUMBER(38,16), 
	"PX_SETTLE" NUMBER(38,16), 
	"PX_SETTLE_LAST_DT" DATE, 
	"EXCHANGE_DELAY" VARCHAR2(255 BYTE), 
	"PX_OPEN" NUMBER(38,16), 
	"PX_HIGH" NUMBER(38,16), 
	"PX_LOW" NUMBER(38,16), 
	"CONTRACT_VALUE" NUMBER(38,16), 
	"EQY_IND_DPS_ANNUAL_NET" NUMBER(38,12), 
	"YLD_YTC_MID" NUMBER(38,2), 
	"YLD_YTM_MID" NUMBER(38,6), 
	"INDEX_FACTOR" NUMBER(38,16), 
	"DVD_YLD_12M_GROSS" NUMBER(38,16), 
	"SH_OUT_FLOAT" NUMBER(38,12)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 ROW STORE COMPRESS ADVANCED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
  PARTITION BY LIST ("RIM_VALUE_DATE") 
  SUBPARTITION BY LIST ("SYS_PARTITION_ID") 
 (PARTITION "P_20251030"  VALUES (TO_DATE(' 2025-10-30 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202510300101045N"  VALUES ('202510300101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251031"  VALUES (TO_DATE(' 2025-10-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202510310101045N"  VALUES ('202510310101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251103"  VALUES (TO_DATE(' 2025-11-03 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511030101045N"  VALUES ('202511030101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251104"  VALUES (TO_DATE(' 2025-11-04 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511040101045N"  VALUES ('202511040101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251105"  VALUES (TO_DATE(' 2025-11-05 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511050101045N"  VALUES ('202511050101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251106"  VALUES (TO_DATE(' 2025-11-06 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511060101045N"  VALUES ('202511060101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251107"  VALUES (TO_DATE(' 2025-11-07 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511070101045N"  VALUES ('202511070101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251110"  VALUES (TO_DATE(' 2025-11-10 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511100101045N"  VALUES ('202511100101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251111"  VALUES (TO_DATE(' 2025-11-11 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511110101045N"  VALUES ('202511110101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251112"  VALUES (TO_DATE(' 2025-11-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511120101045N"  VALUES ('202511120101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251113"  VALUES (TO_DATE(' 2025-11-13 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511130101045N"  VALUES ('202511130101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251114"  VALUES (TO_DATE(' 2025-11-14 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511140101045N"  VALUES ('202511140101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251117"  VALUES (TO_DATE(' 2025-11-17 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511170101045N"  VALUES ('202511170101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251118"  VALUES (TO_DATE(' 2025-11-18 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511180101045N"  VALUES ('202511180101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251119"  VALUES (TO_DATE(' 2025-11-19 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511190101045N"  VALUES ('202511190101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251120"  VALUES (TO_DATE(' 2025-11-20 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511200101045N"  VALUES ('202511200101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251121"  VALUES (TO_DATE(' 2025-11-21 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511210101045N"  VALUES ('202511210101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251124"  VALUES (TO_DATE(' 2025-11-24 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511240101045N"  VALUES ('202511240101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251125"  VALUES (TO_DATE(' 2025-11-25 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511250101045N"  VALUES ('202511250101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251126"  VALUES (TO_DATE(' 2025-11-26 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511260101045N"  VALUES ('202511260101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251127"  VALUES (TO_DATE(' 2025-11-27 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511270101045N"  VALUES ('202511270101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251128"  VALUES (TO_DATE(' 2025-11-28 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202511280101045N"  VALUES ('202511280101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251201"  VALUES (TO_DATE(' 2025-12-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512010101045N"  VALUES ('202512010101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251202"  VALUES (TO_DATE(' 2025-12-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512020101045N"  VALUES ('202512020101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251203"  VALUES (TO_DATE(' 2025-12-03 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512030101045N"  VALUES ('202512030101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251204"  VALUES (TO_DATE(' 2025-12-04 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512040101045N"  VALUES ('202512040101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251205"  VALUES (TO_DATE(' 2025-12-05 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512050101045N"  VALUES ('202512050101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251208"  VALUES (TO_DATE(' 2025-12-08 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512080101045N"  VALUES ('202512080101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251209"  VALUES (TO_DATE(' 2025-12-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512090101045N"  VALUES ('202512090101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251210"  VALUES (TO_DATE(' 2025-12-10 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512100101045N"  VALUES ('202512100101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251211"  VALUES (TO_DATE(' 2025-12-11 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512110101045N"  VALUES ('202512110101045N') SEGMENT CREATION IMMEDIATE 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251212"  VALUES (TO_DATE(' 2025-12-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512120101045N"  VALUES ('202512120101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251215"  VALUES (TO_DATE(' 2025-12-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512150101045N"  VALUES ('202512150101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251216"  VALUES (TO_DATE(' 2025-12-16 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512160101045N"  VALUES ('202512160101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251217"  VALUES (TO_DATE(' 2025-12-17 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512170101045N"  VALUES ('202512170101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251218"  VALUES (TO_DATE(' 2025-12-18 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512180101045N"  VALUES ('202512180101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251219"  VALUES (TO_DATE(' 2025-12-19 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512190101045N"  VALUES ('202512190101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251222"  VALUES (TO_DATE(' 2025-12-22 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512220101045N"  VALUES ('202512220101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251223"  VALUES (TO_DATE(' 2025-12-23 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512230101045N"  VALUES ('202512230101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251224"  VALUES (TO_DATE(' 2025-12-24 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512240101045N"  VALUES ('202512240101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251226"  VALUES (TO_DATE(' 2025-12-26 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512260101045N"  VALUES ('202512260101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251229"  VALUES (TO_DATE(' 2025-12-29 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512290101045N"  VALUES ('202512290101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251230"  VALUES (TO_DATE(' 2025-12-30 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512300101045N"  VALUES ('202512300101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20251231"  VALUES (TO_DATE(' 2025-12-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202512310101045N"  VALUES ('202512310101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260102"  VALUES (TO_DATE(' 2026-01-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601020101045N"  VALUES ('202601020101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260105"  VALUES (TO_DATE(' 2026-01-05 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601050101045N"  VALUES ('202601050101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260106"  VALUES (TO_DATE(' 2026-01-06 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601060101045N"  VALUES ('202601060101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260107"  VALUES (TO_DATE(' 2026-01-07 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601070101045N"  VALUES ('202601070101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260108"  VALUES (TO_DATE(' 2026-01-08 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601080101045N"  VALUES ('202601080101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260109"  VALUES (TO_DATE(' 2026-01-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601090101045N"  VALUES ('202601090101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260112"  VALUES (TO_DATE(' 2026-01-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601120101045N"  VALUES ('202601120101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260113"  VALUES (TO_DATE(' 2026-01-13 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601130101045N"  VALUES ('202601130101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260114"  VALUES (TO_DATE(' 2026-01-14 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601140101045N"  VALUES ('202601140101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260115"  VALUES (TO_DATE(' 2026-01-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601150101045N"  VALUES ('202601150101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260116"  VALUES (TO_DATE(' 2026-01-16 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601160101045N"  VALUES ('202601160101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260119"  VALUES (TO_DATE(' 2026-01-19 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601190101045N"  VALUES ('202601190101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260120"  VALUES (TO_DATE(' 2026-01-20 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601200101045N"  VALUES ('202601200101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260121"  VALUES (TO_DATE(' 2026-01-21 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601210101045N"  VALUES ('202601210101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260122"  VALUES (TO_DATE(' 2026-01-22 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601220101045N"  VALUES ('202601220101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260123"  VALUES (TO_DATE(' 2026-01-23 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601230101045N"  VALUES ('202601230101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260126"  VALUES (TO_DATE(' 2026-01-26 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601260101045N"  VALUES ('202601260101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260127"  VALUES (TO_DATE(' 2026-01-27 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601270101045N"  VALUES ('202601270101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260128"  VALUES (TO_DATE(' 2026-01-28 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601280101045N"  VALUES ('202601280101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260129"  VALUES (TO_DATE(' 2026-01-29 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601290101045N"  VALUES ('202601290101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260130"  VALUES (TO_DATE(' 2026-01-30 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202601300101045N"  VALUES ('202601300101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) , 
 PARTITION "P_20260202"  VALUES (TO_DATE(' 2026-02-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED 
 ( SUBPARTITION "202602020101045N"  VALUES ('202602020101045N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ROW STORE COMPRESS ADVANCED ) ) ;

   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."REF_SEC_UNIQUE_KEY" IS 'The instrument that is used as a proxy for a proxy-based instrument.
The proxy-based instrument inherits its characteristics from the reference instrument.';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."FACTOR" IS 'The portion of the reference instrument represented by the reference instrument. 
It is applied to the proxy-based instrument to derive its price.  It may be 1 or less.';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."REF_CURR" IS 'The currency of the reference instrument';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."REF_SEC_STD_ID" IS 'Smartco will create a native code';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."DUR_ADJ_MID" IS 'Mid Modified Duration';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."YLD_CNV_MID" IS 'Mid Yield To Convention';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."CURRENT_TRR_1MO" IS 'Current Total return 1M';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."CURRENT_TRR_3MO" IS 'Current Total return 3M';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."CURRENT_TRR_YTD" IS 'Current Total return YTD';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."CURRENT_TRR_1YR" IS 'Current Total return 1Y';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."CURRENT_ANN_TRR_3YR" IS 'Current Total return 3Y';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."CURRENT_ANN_TRR_5YR" IS 'Current Total return 5Y';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."VOLATILITY_360D" IS 'Volatility 360D';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."VOLATILITY_360D_CALC" IS 'Volatility 360D Calc';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."REF_WEALTH" IS 'Quote Final for Wealth';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."ID_ISIN" IS 'ISIN';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."AGG_AVG_VOL_90D" IS 'Aggregated Average Volume 90D based on this business rule Aggregated Average Volume';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."AGG_AVG_VOL_180D" IS 'Aggregated Average Volume 180D based on this business rule Aggregated Average Volume';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."EXCHANGE" IS 'Code MIC';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."CURRENCY" IS 'Code ISO 3';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."COUNTRY" IS 'Code ISO 2';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."FLAG_PRIMARY_MARKET" IS 'Indique si il s''agit du march  principal (scope : Equity)';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."AGG_AVG_VOL_30D" IS 'Aggregated Average Volume 30D based on this business rule Aggregated Average Volume';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."BETA" IS 'Coefficient BETA de l''instrument';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."CHG_PCT_1M" IS 'Price change 1M';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."CHG_PCT_3M" IS 'Price change 3M';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."CHG_PCT_6M" IS 'Price change 6M';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."CHG_PCT_1YR" IS 'Price change 1Y';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."CHG_PCT_MTD" IS 'Price change MTD';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."CHG_PCT_QTD" IS 'Price change QTD';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."CHG_PCT_YTD" IS 'Price change YTD';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."CV_MODEL_VEGA" IS 'Convertible Model Vega';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."CV_MODEL_DELTA_V" IS 'Convertible Model Delta V';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."CV_MODEL_GAMMA_V" IS 'Convertible Model Gamma V';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."FUT_CNV_RISK_FRSK" IS 'Futures Conventional Risk';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."FUT_PX_VAL_BP" IS 'Value of 1 Basis Point';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."DELTA_MID" IS 'Delta Mid Price';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."GAMMA_MID" IS 'Gamma Mid Price';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."VEGA_MID" IS 'Vega Mid Price';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."INTEREST_RATE_SENSITIVITY" IS 'Interest rate sensitivity';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."CREDIT_SENSITIVITY" IS 'Credit Sensitivity';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."DVD_DECLARED_DT" IS 'DVD_DECLARED_DT';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."DVD_RECORD_DT" IS 'DVD_RECORD_DT';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."DVD_PAY_DT" IS 'DVD_PAY_DT';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."LAST_DPS_GROSS" IS 'LAST_DPS_GROSS';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."NET_ASSET" IS 'Net Asset Value';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."NAV_CRNCY" IS 'Currency code that the Net Asset Value (NAV) is denominated in, ';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."INTRINSIC_VALUE" IS 'Instrument intrinsic value';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."TOT_RETURN_INDEX_NET_DVDS" IS 'One day total return index as of today,';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."AVG_YIELD" IS 'Average yield';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."PRICE_INDEX" IS 'PRICE_INDEX';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."MACAULAY_DURATION" IS 'MACAULAY_DURATION ';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."MODIFIED_DURATION" IS 'MODIFIED_DURATION ';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."MONEY_DURATION" IS 'dollar value of an 01';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."AVG_COUPON" IS 'Average coupon';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."AVG_MATURITY" IS 'Average Maturity';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."FUT_AGGTE_OPEN_INT" IS 'The total number of futures contracts that have not been closed, liquidated, or delivered for all currently listed contracts in a series,';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."PX_SETTLE" IS 'settle price';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."PX_SETTLE_LAST_DT" IS 'last date of settle price';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."EXCHANGE_DELAY" IS 'delay in minutes';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."PX_OPEN" IS 'open price';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."PX_HIGH" IS 'high price';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."PX_LOW" IS 'low price';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."CONTRACT_VALUE" IS 'The total cost of the security,';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."EQY_IND_DPS_ANNUAL_NET" IS 'The most recent dividend per share (net) annualized,';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."YLD_YTC_MID" IS 'Mid Yield To Next Call';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."YLD_YTM_MID" IS 'Mid Yield To Maturity';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."INDEX_FACTOR" IS 'Index factor';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."DVD_YLD_12M_GROSS" IS 'Dividend 12 Month Yld - Gross';
   COMMENT ON COLUMN "SDH"."TB_SMARTCO_INSTRUMENTDATA"."SH_OUT_FLOAT" IS 'outstanding shares float';
  GRANT SELECT ON "SDH"."TB_SMARTCO_INSTRUMENTDATA" TO "TMF_SERVICES" WITH GRANT OPTION;
--------------------------------------------------------
--  Constraints for Table TB_SMARTCO_INSTRUMENTDATA
--------------------------------------------------------

  ALTER TABLE "SDH"."TB_SMARTCO_INSTRUMENTDATA" MODIFY ("SYS_CREAT_DTMS" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_INSTRUMENTDATA" MODIFY ("SYS_CREAT_PROCSS_USR_ID" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_INSTRUMENTDATA" MODIFY ("SYS_PARTITION_ID" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_INSTRUMENTDATA" MODIFY ("RIM_VALUE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_INSTRUMENTDATA" MODIFY ("RIM_VALUE_TM" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_INSTRUMENTDATA" MODIFY ("RIM_LOAD_TIMELN_VAL" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_INSTRUMENTDATA" MODIFY ("DIV_NAME" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_INSTRUMENTDATA" MODIFY ("SYS_NAME" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_INSTRUMENTDATA" MODIFY ("SIT_CODE" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_SMARTCO_INSTRUMENTDATA" MODIFY ("RIM_SID" NOT NULL ENABLE);
