--------------------------------------------------------
--  File created - Tuesday-February-24-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TB_TRADE_MUREX_LST_OPT
--------------------------------------------------------

  CREATE TABLE "SDH"."TB_TRADE_MUREX_LST_OPT" 
   (	"SYS_CREAT_DTMS" DATE, 
	"SYS_CREAT_PROCSS_USR_ID" VARCHAR2(100 BYTE), 
	"SYS_UPDT_DTMS" DATE, 
	"SYS_UPDT_PROCSS_USR_ID" VARCHAR2(100 BYTE), 
	"SYS_PARTITION_ID" VARCHAR2(30 BYTE), 
	"SYS_VALUE_DATE" DATE, 
	"SYS_VALUE_TM" VARCHAR2(8 BYTE), 
	"SYS_LOAD_TIMELN_VAL" VARCHAR2(10 BYTE), 
	"SYS_LOAD_TIMELN_TIMESTAMP" DATE, 
	"DIV_NAME" VARCHAR2(30 BYTE), 
	"SYS_NAME" VARCHAR2(30 BYTE), 
	"SIT_CODE" VARCHAR2(10 BYTE), 
	"TRR_SID" NUMBER(38,0), 
	"MSG_RECV_TMSTMP" VARCHAR2(255 BYTE), 
	"REPORTING_TMSTMP" VARCHAR2(255 BYTE), 
	"EVENT_DATE" DATE, 
	"SUBMITTING_ENTITY" VARCHAR2(255 BYTE), 
	"REPORTING_ENTITY" VARCHAR2(255 BYTE), 
	"EXEC_AGENT_ID" VARCHAR2(255 BYTE), 
	"CPTY1_ID_TYPE" VARCHAR2(255 BYTE), 
	"CPTY1" VARCHAR2(255 BYTE), 
	"CPTY1_NATURE" VARCHAR2(255 BYTE), 
	"CPTY1_CORPORATE_SECTOR" VARCHAR2(255 BYTE), 
	"CPTY1_CLEARING_THRESHOLD" VARCHAR2(255 BYTE), 
	"TRADING_CAPACITY" VARCHAR2(255 BYTE), 
	"CPTY2_ID_TYPE" VARCHAR2(255 BYTE), 
	"CPTY2_ID" VARCHAR2(255 BYTE), 
	"CPTY2" VARCHAR2(255 BYTE), 
	"CPTY2_COUNTRY" VARCHAR2(255 BYTE), 
	"CPTY2_NATURE" VARCHAR2(255 BYTE), 
	"CPTY2_CORPORATE_SECTOR" VARCHAR2(255 BYTE), 
	"CPTY2_CLEARING_THRESHOLD" VARCHAR2(255 BYTE), 
	"CPTY2_REPORTING_OBLIG" VARCHAR2(255 BYTE), 
	"BROKER_ID" VARCHAR2(255 BYTE), 
	"CLEARING_MEMBER" VARCHAR2(255 BYTE), 
	"BENEFICIARY_ID_TYPE" VARCHAR2(255 BYTE), 
	"BENEFICIARY_ID" VARCHAR2(255 BYTE), 
	"DIRECTION" VARCHAR2(255 BYTE), 
	"DIRECTION_LEG1" VARCHAR2(255 BYTE), 
	"DIRECTION_LEG2" VARCHAR2(255 BYTE), 
	"DRCTL_LNKD_COMM_TRSR" VARCHAR2(255 BYTE), 
	"UTI" VARCHAR2(255 BYTE), 
	"REPORT_TRACKING_NUMBER" VARCHAR2(255 BYTE), 
	"PRIOR_UTI" VARCHAR2(255 BYTE), 
	"SUBSEQUENT_POSITION_UTI" VARCHAR2(255 BYTE), 
	"PTRR_ID" VARCHAR2(255 BYTE), 
	"PACKAGE_ID" VARCHAR2(255 BYTE), 
	"PRODUCT_ID_TYPE" VARCHAR2(255 BYTE), 
	"PRODUCT_ID" VARCHAR2(255 BYTE), 
	"ISIN" VARCHAR2(255 BYTE), 
	"UPI" VARCHAR2(255 BYTE), 
	"PRODUCT_CLASSIFICATION" VARCHAR2(255 BYTE), 
	"CONTRACT_TYPE" VARCHAR2(255 BYTE), 
	"ASSET_CLASS" VARCHAR2(255 BYTE), 
	"DERIVATIVE_BASED_CRYPTO" VARCHAR2(255 BYTE), 
	"UNDERLYING_ID_TYPE" VARCHAR2(255 BYTE), 
	"UNDERLYING_ID" VARCHAR2(255 BYTE), 
	"UNDERLYING_INDEX_IND" VARCHAR2(255 BYTE), 
	"UNDERLYING_INDEX_NAME" VARCHAR2(255 BYTE), 
	"CUSTOM_BASKET_CODE" VARCHAR2(255 BYTE), 
	"BASKET_CONSTITUENTS_ID" VARCHAR2(255 BYTE), 
	"SETTLEMENT_CCY1" VARCHAR2(255 BYTE), 
	"SETTLEMENT_CCY2" VARCHAR2(255 BYTE), 
	"VALUATION_AMT" NUMBER(38,12), 
	"VALUATION_CCY" VARCHAR2(255 BYTE), 
	"VALUATION_TMSTMP" VARCHAR2(255 BYTE), 
	"VALUATION_METHOD" VARCHAR2(255 BYTE), 
	"DELTA" NUMBER(38,16), 
	"COLL_PORTFOLIO_ID" VARCHAR2(255 BYTE), 
	"COLL_PORTFOLIO_CODE" VARCHAR2(255 BYTE), 
	"CONFIRMATION_TMSTMP" VARCHAR2(255 BYTE), 
	"CONFIRMED" VARCHAR2(255 BYTE), 
	"CLEARING_OBLIGATION" VARCHAR2(255 BYTE), 
	"CLEARED" VARCHAR2(255 BYTE), 
	"CLEARING_TMSTMP" VARCHAR2(255 BYTE), 
	"CENTRAL_CPTY" VARCHAR2(255 BYTE), 
	"OTH_MASTER_AGEERMENT_TYPE" VARCHAR2(255 BYTE), 
	"MASTER_AGREEMENT_TYPE" VARCHAR2(255 BYTE), 
	"MASTER_AGREEMENT_VERSION" VARCHAR2(255 BYTE), 
	"INTRAGROUP" VARCHAR2(255 BYTE), 
	"PTRR" VARCHAR2(255 BYTE), 
	"PTRR_TECHNIQUE_TYPE" VARCHAR2(255 BYTE), 
	"PTRR_SERVICE_PROVIDER" VARCHAR2(255 BYTE), 
	"EXECUTION_VENUE" VARCHAR2(255 BYTE), 
	"COMPRESSION" VARCHAR2(255 BYTE), 
	"EXECUTION_TMSTMP" VARCHAR2(255 BYTE), 
	"EFF_DATE" DATE, 
	"EXP_DATE" DATE, 
	"EARLY_TERM_DATE" DATE, 
	"FINAL_CONTRACT_SETTL_DATE" DATE, 
	"DELIVERY_TYPE" VARCHAR2(255 BYTE), 
	"PRICE_TYPE" VARCHAR2(255 BYTE), 
	"PRICE" NUMBER(38,12), 
	"PRICE_MULTIPLIER" VARCHAR2(255 BYTE), 
	"PRICE_CCY" VARCHAR2(255 BYTE), 
	"PRICE_UNJSTD_EFFECT_DATE" DATE, 
	"PRICE_UNJSTD_END_DATE" DATE, 
	"PRICE_IN_EFFECT_TYPE" VARCHAR2(255 BYTE), 
	"PRICE_IN_EFFECT" VARCHAR2(255 BYTE), 
	"PRICE_IN_EFFECT_CCY" VARCHAR2(255 BYTE), 
	"PKG_TRANSACTN_PRICE_TYPE" VARCHAR2(255 BYTE), 
	"PKG_TRANSACTN_PRICE" NUMBER(38,12), 
	"PKG_TRANSACTN_PRICE_CCY" VARCHAR2(255 BYTE), 
	"NOTIONAL_AMT_LEG1" NUMBER(38,12), 
	"NOTIONAL_CCY_LEG1" VARCHAR2(255 BYTE), 
	"NOTIONAL_AMT_EFF_DTE_LEG1" VARCHAR2(255 BYTE), 
	"NOTIONAL_AMT_END_DTE_LEG1" VARCHAR2(255 BYTE), 
	"NOTIONAL_AMT_EFFECT_LEG1" VARCHAR2(255 BYTE), 
	"NOTIONAL_AMT_EFFECT_CCY_S1" VARCHAR2(255 BYTE), 
	"TOTAL_NOTIONAL_QTY_LEG1" NUMBER(38,12), 
	"NOTIONAL_QTY_EFF_DATE_LEG1" VARCHAR2(255 BYTE), 
	"NOTIONAL_QTY_END_DATE_LEG1" VARCHAR2(255 BYTE), 
	"NOTIONAL_QTY_IN_EFFECT_S1" VARCHAR2(255 BYTE), 
	"NOTIONAL_AMT_LEG2" NUMBER(38,12), 
	"NOTIONAL_CCY_LEG2" VARCHAR2(255 BYTE), 
	"NOTIONAL_AMT_EFF_DATE_LEG2" VARCHAR2(255 BYTE), 
	"NOTIONAL_AMT_END_DATE_LEG2" VARCHAR2(255 BYTE), 
	"NOTIONAL_AMT_EFFECT_LEG2" VARCHAR2(255 BYTE), 
	"NOTIONAL_AMT_EFFECT_CCY_S2" VARCHAR2(255 BYTE), 
	"TOTAL_NOTIONAL_QTY_LEG2" NUMBER(38,12), 
	"NOTIONAL_QTY_EFF_DATE_LEG2" VARCHAR2(255 BYTE), 
	"NOTIONAL_QTY_END_DATE_LEG2" VARCHAR2(255 BYTE), 
	"NOTIONAL_QTY_IN_EFFECT_S2" VARCHAR2(255 BYTE), 
	"QTY_TYPE" VARCHAR2(255 BYTE), 
	"QTY" NUMBER(38,12), 
	"OTHER_PAY_TYPE" VARCHAR2(255 BYTE), 
	"OTHER_PAY_AMOUNT" VARCHAR2(255 BYTE), 
	"OTHER_PAY_CCY" VARCHAR2(255 BYTE), 
	"OTHER_PAY_DATE" VARCHAR2(255 BYTE), 
	"OTHER_PAY_PAYER_TYPE" VARCHAR2(255 BYTE), 
	"OTHER_PAY_PAYER" VARCHAR2(255 BYTE), 
	"OTHER_PAY_RECEIVER" VARCHAR2(255 BYTE), 
	"OTHER_PAY_RECEIVER_TYPE" VARCHAR2(255 BYTE), 
	"FIX_RATE_LEG1" VARCHAR2(255 BYTE), 
	"FIX_RATE_DAY_CNT_CONV_LEG1" VARCHAR2(255 BYTE), 
	"FIX_RATE_DAY_CNT_NARR_LEG1" VARCHAR2(255 BYTE), 
	"FIX_RATE_PAY_FRQ_PRD_LEG1" VARCHAR2(255 BYTE), 
	"FIX_RATE_PAY_FRQ_MULTI_S1" VARCHAR2(255 BYTE), 
	"FLOAT_RATE_ID_LEG1" VARCHAR2(255 BYTE), 
	"FLOAT_RATE_IND_LEG1" VARCHAR2(255 BYTE), 
	"FLOAT_RATE_NAME_LEG1" VARCHAR2(255 BYTE), 
	"FLOAT_RATE_DAY_CNT_CONV_S1" VARCHAR2(255 BYTE), 
	"FLOAT_RATE_PAY_FRQ_PERD_S1" VARCHAR2(255 BYTE), 
	"FLOAT_RATE_PAY_FRQ_MULT_S1" VARCHAR2(255 BYTE), 
	"FLOAT_RATE_REF_PRD_TIME_S1" VARCHAR2(255 BYTE), 
	"FLOAT_RATE_REF_PRD_MULT_S1" VARCHAR2(255 BYTE), 
	"FLOAT_RATE_RST_FRQ_PRD_S1" VARCHAR2(255 BYTE), 
	"FLOAT_RATE_RST_FRQ_MULT_S1" VARCHAR2(255 BYTE), 
	"SPREAD_TYPE_LEG1" VARCHAR2(255 BYTE), 
	"SPREAD_LEG1" VARCHAR2(255 BYTE), 
	"SPREAD_CCY_LEG1" VARCHAR2(255 BYTE), 
	"FIX_RATE_LEG2" VARCHAR2(255 BYTE), 
	"FIX_RATE_DAY_CNT_CONV_LEG2" VARCHAR2(255 BYTE), 
	"FIX_RATE_DAY_CNT_NARR_LEG2" VARCHAR2(255 BYTE), 
	"FIX_RATE_PAY_FRQ_PRD_LEG2" VARCHAR2(255 BYTE), 
	"FIX_RATE_PAY_FRQ_MULT_LEG2" VARCHAR2(255 BYTE), 
	"FLOAT_RATE_ID_LEG2" VARCHAR2(255 BYTE), 
	"FLOAT_RATE_INDICATOR_LEG2" VARCHAR2(255 BYTE), 
	"FLOAT_RATE_NAME_LEG2" VARCHAR2(255 BYTE), 
	"FLOAT_RATE_DAY_CNT_CONV_S2" VARCHAR2(255 BYTE), 
	"FLOAT_RATE_PAY_FRQ_PRD_S2" VARCHAR2(255 BYTE), 
	"FLOAT_RATE_PAY_FRQ_MULT_S2" VARCHAR2(255 BYTE), 
	"FLOAT_RATE_REF_PRD_TIME_S2" VARCHAR2(255 BYTE), 
	"FLOAT_RATE_REF_PRD_MULT_S2" VARCHAR2(255 BYTE), 
	"FLOAT_RATE_RST_FRQ_PRD_S2" VARCHAR2(255 BYTE), 
	"FLOAT_RATE_RST_FRQ_MULT_S2" VARCHAR2(255 BYTE), 
	"SPREAD_TYPE_LEG2" VARCHAR2(255 BYTE), 
	"SPREAD_LEG2" VARCHAR2(255 BYTE), 
	"SPREAD_CCY_LEG2" VARCHAR2(255 BYTE), 
	"PKG_SPREAD_TYPE" VARCHAR2(255 BYTE), 
	"PKG_TRANSACTION_SPREAD" VARCHAR2(255 BYTE), 
	"PKG_TRANSACTION_SPREAD_CCY" VARCHAR2(255 BYTE), 
	"EXCHANGE_RATE" VARCHAR2(255 BYTE), 
	"FWD_EXCHANGE_RATE" VARCHAR2(255 BYTE), 
	"EXCHANGE_RATE_BASIS" VARCHAR2(255 BYTE), 
	"BASE_PRODUCT" VARCHAR2(255 BYTE), 
	"SUB_PRODUCT" VARCHAR2(255 BYTE), 
	"SUB_PRODUCT2" VARCHAR2(255 BYTE), 
	"DELIVERY_POINT" VARCHAR2(255 BYTE), 
	"INTERCONNCT_POINT" VARCHAR2(255 BYTE), 
	"LOAD_TYPE" VARCHAR2(255 BYTE), 
	"DELIVERY_START_TIME" VARCHAR2(255 BYTE), 
	"DELIVERY_END_TIME" VARCHAR2(255 BYTE), 
	"DELIVERY_START_DATE" DATE, 
	"DELIVERY_END_DATE" DATE, 
	"DURATION" VARCHAR2(255 BYTE), 
	"DAYS_OF_WEEK" VARCHAR2(255 BYTE), 
	"DELIVERY_CAPACITY" VARCHAR2(255 BYTE), 
	"QTY_UNIT" VARCHAR2(255 BYTE), 
	"PRICE_TIME_INTERVL_QTY" VARCHAR2(255 BYTE), 
	"PRICE_TIME_INTERVL_QTY_CCY" VARCHAR2(255 BYTE), 
	"OPTION_TYPE" VARCHAR2(255 BYTE), 
	"OPTION_STYLE" VARCHAR2(255 BYTE), 
	"STRIKE_PRICE_TYPE" VARCHAR2(255 BYTE), 
	"STRIKE_PRICE" NUMBER(38,12), 
	"STRIKE_PRICE_CCY" VARCHAR2(255 BYTE), 
	"STRIKE_PRICE_EFF_DATE" VARCHAR2(255 BYTE), 
	"STRIKE_PRICE_END_DATE" VARCHAR2(255 BYTE), 
	"STRIKE_PRICE_IN_EFFCT_TYPE" VARCHAR2(255 BYTE), 
	"STRIKE_PRICE_IN_EFFCT_DATE" VARCHAR2(255 BYTE), 
	"STRIKE_PRICE_IN_EFFCT_CCY" VARCHAR2(255 BYTE), 
	"STRKE_PRICE_CCY_PAIR" VARCHAR2(255 BYTE), 
	"OPTION_PREMIUM_AMT" NUMBER(38,12), 
	"OPTION_PREMIUM_CCY" VARCHAR2(255 BYTE), 
	"OPTION_PREMIUM_PAY_DATE" DATE, 
	"UNDERLYING_MATURITY_DATE" DATE, 
	"SENIORITY" VARCHAR2(255 BYTE), 
	"REF_ENTITY" VARCHAR2(255 BYTE), 
	"PAY_FRQ" VARCHAR2(255 BYTE), 
	"CALC_BASIS" VARCHAR2(255 BYTE), 
	"SERIES" VARCHAR2(255 BYTE), 
	"VERSION" VARCHAR2(255 BYTE), 
	"INDEX_FACTOR" VARCHAR2(255 BYTE), 
	"TRANCHE" VARCHAR2(255 BYTE), 
	"CDS_INDEX_ATTACH_POINT" VARCHAR2(255 BYTE), 
	"CDS_INDEX_DETACH_POINT" VARCHAR2(255 BYTE), 
	"ACTION_TYPE" VARCHAR2(255 BYTE), 
	"EVENT_TYPE" VARCHAR2(255 BYTE), 
	"LEVEL_VAL" VARCHAR2(255 BYTE), 
	"RECON_FLG" VARCHAR2(255 BYTE), 
	"PAIR_SRC" VARCHAR2(255 BYTE), 
	"TRADE_REF_ID" VARCHAR2(255 BYTE), 
	"CNT_VERSION" NUMBER(38,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
  PARTITION BY LIST ("SYS_VALUE_DATE") 
  SUBPARTITION BY LIST ("SYS_PARTITION_ID") 
 (PARTITION "P_20251030"  VALUES (TO_DATE(' 2025-10-30 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202510300101001N"  VALUES ('202510300101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251031"  VALUES (TO_DATE(' 2025-10-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202510310101001N"  VALUES ('202510310101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251104"  VALUES (TO_DATE(' 2025-11-04 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511040101001N"  VALUES ('202511040101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251105"  VALUES (TO_DATE(' 2025-11-05 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511050101001N"  VALUES ('202511050101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251107"  VALUES (TO_DATE(' 2025-11-07 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511070101001N"  VALUES ('202511070101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251110"  VALUES (TO_DATE(' 2025-11-10 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511100101001N"  VALUES ('202511100101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251112"  VALUES (TO_DATE(' 2025-11-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511120101001N"  VALUES ('202511120101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251113"  VALUES (TO_DATE(' 2025-11-13 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511130101001N"  VALUES ('202511130101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251114"  VALUES (TO_DATE(' 2025-11-14 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511140101001N"  VALUES ('202511140101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251117"  VALUES (TO_DATE(' 2025-11-17 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511170101001N"  VALUES ('202511170101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251118"  VALUES (TO_DATE(' 2025-11-18 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511180101001N"  VALUES ('202511180101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251119"  VALUES (TO_DATE(' 2025-11-19 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511190101001N"  VALUES ('202511190101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251120"  VALUES (TO_DATE(' 2025-11-20 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511200101001N"  VALUES ('202511200101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251121"  VALUES (TO_DATE(' 2025-11-21 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511210101001N"  VALUES ('202511210101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251124"  VALUES (TO_DATE(' 2025-11-24 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511240101001N"  VALUES ('202511240101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251125"  VALUES (TO_DATE(' 2025-11-25 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511250101001N"  VALUES ('202511250101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251126"  VALUES (TO_DATE(' 2025-11-26 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202511260101001N"  VALUES ('202511260101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251202"  VALUES (TO_DATE(' 2025-12-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512020101001N"  VALUES ('202512020101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251205"  VALUES (TO_DATE(' 2025-12-05 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512050101001N"  VALUES ('202512050101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251208"  VALUES (TO_DATE(' 2025-12-08 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512080101001N"  VALUES ('202512080101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251209"  VALUES (TO_DATE(' 2025-12-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512090101001N"  VALUES ('202512090101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251210"  VALUES (TO_DATE(' 2025-12-10 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512100101001N"  VALUES ('202512100101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251211"  VALUES (TO_DATE(' 2025-12-11 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512110101001N"  VALUES ('202512110101001N') SEGMENT CREATION IMMEDIATE 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251212"  VALUES (TO_DATE(' 2025-12-12 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512120101001N"  VALUES ('202512120101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251215"  VALUES (TO_DATE(' 2025-12-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512150101001N"  VALUES ('202512150101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251217"  VALUES (TO_DATE(' 2025-12-17 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512170101001N"  VALUES ('202512170101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251218"  VALUES (TO_DATE(' 2025-12-18 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512180101001N"  VALUES ('202512180101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251219"  VALUES (TO_DATE(' 2025-12-19 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512190101001N"  VALUES ('202512190101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251226"  VALUES (TO_DATE(' 2025-12-26 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512260101001N"  VALUES ('202512260101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20251229"  VALUES (TO_DATE(' 2025-12-29 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202512290101001N"  VALUES ('202512290101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260106"  VALUES (TO_DATE(' 2026-01-06 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601060101001N"  VALUES ('202601060101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260107"  VALUES (TO_DATE(' 2026-01-07 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601070101001N"  VALUES ('202601070101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260108"  VALUES (TO_DATE(' 2026-01-08 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601080101001N"  VALUES ('202601080101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260109"  VALUES (TO_DATE(' 2026-01-09 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601090101001N"  VALUES ('202601090101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260113"  VALUES (TO_DATE(' 2026-01-13 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601130101001N"  VALUES ('202601130101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260114"  VALUES (TO_DATE(' 2026-01-14 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601140101001N"  VALUES ('202601140101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260115"  VALUES (TO_DATE(' 2026-01-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601150101001N"  VALUES ('202601150101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260116"  VALUES (TO_DATE(' 2026-01-16 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601160101001N"  VALUES ('202601160101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260120"  VALUES (TO_DATE(' 2026-01-20 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601200101001N"  VALUES ('202601200101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260122"  VALUES (TO_DATE(' 2026-01-22 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601220101001N"  VALUES ('202601220101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260123"  VALUES (TO_DATE(' 2026-01-23 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601230101001N"  VALUES ('202601230101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) , 
 PARTITION "P_20260130"  VALUES (TO_DATE(' 2026-01-30 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 ( SUBPARTITION "202601300101001N"  VALUES ('202601300101001N') SEGMENT CREATION DEFERRED 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_SDH_DATA" 
 COMPRESS BASIC ) ) ;

   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SYS_CREAT_DTMS" IS 'Record creation date';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SYS_CREAT_PROCSS_USR_ID" IS 'Record creation user';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SYS_UPDT_DTMS" IS 'Record update date';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SYS_UPDT_PROCSS_USR_ID" IS 'Record update user';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SYS_PARTITION_ID" IS 'Partition ID';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SYS_VALUE_DATE" IS 'Business Value date';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SYS_VALUE_TM" IS 'Running actual time';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SYS_LOAD_TIMELN_VAL" IS 'Load timeline (EOD, CORR, )';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SYS_LOAD_TIMELN_TIMESTAMP" IS 'Run date of the extract on Murex side';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."DIV_NAME" IS 'Division name';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SYS_NAME" IS 'System name';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SIT_CODE" IS 'Site code';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."TRR_SID" IS 'Internal identifier';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."MSG_RECV_TMSTMP" IS 'Message Received Timestamp';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."REPORTING_TMSTMP" IS 'Reporting timestamp';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."EVENT_DATE" IS 'Event date';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SUBMITTING_ENTITY" IS 'Report submitting entity ID';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."REPORTING_ENTITY" IS 'Entity responsible for reporting';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."EXEC_AGENT_ID" IS 'Execution Agent ID';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CPTY1_ID_TYPE" IS 'Counterparty 1 (Reporting counterparty) - ID type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CPTY1" IS 'Counterparty 1 (Reporting counterparty)';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CPTY1_NATURE" IS 'Nature of the counterparty 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CPTY1_CORPORATE_SECTOR" IS 'Corporate sector of the counterparty 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CPTY1_CLEARING_THRESHOLD" IS 'Clearing threshold of counterparty 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."TRADING_CAPACITY" IS 'Trading capacity';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CPTY2_ID_TYPE" IS 'Counterparty 2 identifier type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CPTY2_ID" IS 'Counterparty2 identifier';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CPTY2" IS 'Counterparty 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CPTY2_COUNTRY" IS 'Country of the counterparty 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CPTY2_NATURE" IS 'Nature of the counterparty 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CPTY2_CORPORATE_SECTOR" IS 'Corporate sector of the counterparty 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CPTY2_CLEARING_THRESHOLD" IS 'Clearing threshold of counterparty 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CPTY2_REPORTING_OBLIG" IS 'Reporting obligation of the counterparty 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."BROKER_ID" IS 'Broker ID';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CLEARING_MEMBER" IS 'Clearing member';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."BENEFICIARY_ID_TYPE" IS 'Type of ID of the beneficiary';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."BENEFICIARY_ID" IS 'Beneficiary ID';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."DIRECTION" IS 'Direction';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."DIRECTION_LEG1" IS 'Direction of leg 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."DIRECTION_LEG2" IS 'Direction of leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."DRCTL_LNKD_COMM_TRSR" IS 'Directly linked to commercial activity or treasury financing';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."UTI" IS 'UTI';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."REPORT_TRACKING_NUMBER" IS 'Report tracking number';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PRIOR_UTI" IS 'Prior UTI (for one-to-one and one-to-many relations between transactions)';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SUBSEQUENT_POSITION_UTI" IS 'Subsequent position UTI';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PTRR_ID" IS 'PTRR ID';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PACKAGE_ID" IS 'Package identifier';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PRODUCT_ID_TYPE" IS 'Product identification type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PRODUCT_ID" IS 'Product identification';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."ISIN" IS 'ISIN';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."UPI" IS 'Unique product identifier (UPI)';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PRODUCT_CLASSIFICATION" IS 'Product classification';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CONTRACT_TYPE" IS 'Contract type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."ASSET_CLASS" IS 'Asset class';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."DERIVATIVE_BASED_CRYPTO" IS 'Derivative based on crypto-assets';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."UNDERLYING_ID_TYPE" IS 'Underlying identification type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."UNDERLYING_ID" IS 'Underlying identification';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."UNDERLYING_INDEX_IND" IS 'Indicator of the underlying index';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."UNDERLYING_INDEX_NAME" IS 'Name of the underlying index';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CUSTOM_BASKET_CODE" IS 'Custom basket code';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."BASKET_CONSTITUENTS_ID" IS 'Identifier of the baskets constituents';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SETTLEMENT_CCY1" IS 'Settlement currency 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SETTLEMENT_CCY2" IS 'Settlement currency 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."VALUATION_AMT" IS 'Valuation amount';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."VALUATION_CCY" IS 'Valuation currency';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."VALUATION_TMSTMP" IS 'Valuation timestamp';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."VALUATION_METHOD" IS 'Valuation method';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."DELTA" IS 'Delta';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."COLL_PORTFOLIO_ID" IS 'Collateral portfolio indicator';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."COLL_PORTFOLIO_CODE" IS 'Collateral portfolio code';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CONFIRMATION_TMSTMP" IS 'Confirmation timestamp';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CONFIRMED" IS 'Confirmed';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CLEARING_OBLIGATION" IS 'Clearing obligation';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CLEARED" IS 'Cleared';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CLEARING_TMSTMP" IS 'Clearing timestamp';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CENTRAL_CPTY" IS 'Central counterparty';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."OTH_MASTER_AGEERMENT_TYPE" IS 'Master Agreement type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."MASTER_AGREEMENT_TYPE" IS 'Other master agreement type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."MASTER_AGREEMENT_VERSION" IS 'Master Agreement version';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."INTRAGROUP" IS 'Intragroup';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PTRR" IS 'PTRR';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PTRR_TECHNIQUE_TYPE" IS 'Type of PTRR technique';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PTRR_SERVICE_PROVIDER" IS 'PTRR service provider';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."EXECUTION_VENUE" IS 'Venue of execution';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."COMPRESSION" IS 'Compression';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."EXECUTION_TMSTMP" IS 'Execution timestamp';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."EFF_DATE" IS 'Effective date';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."EXP_DATE" IS 'Expiration date';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."EARLY_TERM_DATE" IS 'Early termination date';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FINAL_CONTRACT_SETTL_DATE" IS 'Final contractual settlement date';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."DELIVERY_TYPE" IS 'Delivery type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PRICE_TYPE" IS 'Price - Type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PRICE" IS 'Price';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PRICE_MULTIPLIER" IS 'Price multiplier';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PRICE_CCY" IS 'Price currency';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PRICE_UNJSTD_EFFECT_DATE" IS 'Unadjusted effective date of the price';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PRICE_UNJSTD_END_DATE" IS 'Unadjusted end date of the price';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PRICE_IN_EFFECT_TYPE" IS 'Price in effect between the unadjusted effective and end date - Type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PRICE_IN_EFFECT" IS 'Price in effect between the unadjusted effective and end date';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PRICE_IN_EFFECT_CCY" IS 'Price in effect between the unadjusted effective and end date - Currency';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PKG_TRANSACTN_PRICE_TYPE" IS 'Package transaction price - Type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PKG_TRANSACTN_PRICE" IS 'Package transaction price';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PKG_TRANSACTN_PRICE_CCY" IS 'Package transaction price currency';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."NOTIONAL_AMT_LEG1" IS 'Notional amount of leg 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."NOTIONAL_CCY_LEG1" IS 'Notional currency 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."NOTIONAL_AMT_EFF_DTE_LEG1" IS 'Effective date of the notional amount of leg 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."NOTIONAL_AMT_END_DTE_LEG1" IS 'End date of the notional amount of leg 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."NOTIONAL_AMT_EFFECT_LEG1" IS 'Notional amount in effect on associated effective date of leg 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."NOTIONAL_AMT_EFFECT_CCY_S1" IS 'Notional amount in effect on associated effective date of leg 1 - Currency';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."TOTAL_NOTIONAL_QTY_LEG1" IS 'Total notional quantity of leg 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."NOTIONAL_QTY_EFF_DATE_LEG1" IS 'Effective date of the notional quantity of leg 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."NOTIONAL_QTY_END_DATE_LEG1" IS 'End date of the notional quantity of leg 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."NOTIONAL_QTY_IN_EFFECT_S1" IS 'Notional quantity in effect on associated effective date of leg 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."NOTIONAL_AMT_LEG2" IS 'Notional amount of leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."NOTIONAL_CCY_LEG2" IS 'Notional currency 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."NOTIONAL_AMT_EFF_DATE_LEG2" IS 'Effective date of the notional amount of leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."NOTIONAL_AMT_END_DATE_LEG2" IS 'End date of the notional amount of leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."NOTIONAL_AMT_EFFECT_LEG2" IS 'Notional amount in effect on associated effective date of leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."NOTIONAL_AMT_EFFECT_CCY_S2" IS 'Notional amount in effect on associated effective date of leg 2 - Currency';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."TOTAL_NOTIONAL_QTY_LEG2" IS 'Total notional quantity of leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."NOTIONAL_QTY_EFF_DATE_LEG2" IS 'Effective date of the notional quantity of leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."NOTIONAL_QTY_END_DATE_LEG2" IS 'End date of the notional quantity of leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."NOTIONAL_QTY_IN_EFFECT_S2" IS 'Notional quantity in effect on associated effective date of leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."QTY_TYPE" IS 'Quantity - Type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."QTY" IS 'Quantity';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."OTHER_PAY_TYPE" IS 'Other payment type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."OTHER_PAY_AMOUNT" IS 'Other payment amount';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."OTHER_PAY_CCY" IS 'Other payment currency';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."OTHER_PAY_DATE" IS 'Other payment date';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."OTHER_PAY_PAYER_TYPE" IS 'Other payment payer - Type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."OTHER_PAY_PAYER" IS 'Other payment payer';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."OTHER_PAY_RECEIVER" IS 'Other payment receiver - Type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."OTHER_PAY_RECEIVER_TYPE" IS 'Other payment receiver';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FIX_RATE_LEG1" IS 'Fixed rate of leg 1 or coupon';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FIX_RATE_DAY_CNT_CONV_LEG1" IS 'Fixed rate or coupon day count convention leg 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FIX_RATE_DAY_CNT_NARR_LEG1" IS 'Fixed rate or coupon day count convention leg 1 - Narrative';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FIX_RATE_PAY_FRQ_PRD_LEG1" IS 'Fixed rate or coupon payment frequency period leg 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FIX_RATE_PAY_FRQ_MULTI_S1" IS 'Fixed rate or coupon payment frequency period multiplier leg 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FLOAT_RATE_ID_LEG1" IS 'Identifier of the floating rate of leg 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FLOAT_RATE_IND_LEG1" IS 'Indicator of the floating rate of leg 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FLOAT_RATE_NAME_LEG1" IS 'Name of the floating rate of leg 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FLOAT_RATE_DAY_CNT_CONV_S1" IS 'Floating rate day count convention of leg 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FLOAT_RATE_PAY_FRQ_PERD_S1" IS 'Floating rate payment frequency period of leg 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FLOAT_RATE_PAY_FRQ_MULT_S1" IS 'Floating rate payment frequency period multiplier of leg 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FLOAT_RATE_REF_PRD_TIME_S1" IS 'Floating rate reference period of leg 1 - time period';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FLOAT_RATE_REF_PRD_MULT_S1" IS 'Floating rate reference period of leg 1 - multiplier';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FLOAT_RATE_RST_FRQ_PRD_S1" IS 'Floating rate reset frequency period of leg 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FLOAT_RATE_RST_FRQ_MULT_S1" IS 'Floating rate reset frequency multiplier of leg 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SPREAD_TYPE_LEG1" IS 'Spread of leg 1 - Type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SPREAD_LEG1" IS 'Spread of leg 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SPREAD_CCY_LEG1" IS 'Spread currency of leg 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FIX_RATE_LEG2" IS 'Fixed rate of leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FIX_RATE_DAY_CNT_CONV_LEG2" IS 'Fixed rate day count convention leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FIX_RATE_DAY_CNT_NARR_LEG2" IS 'Fixed rate day count convention leg 2 - Narrative';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FIX_RATE_PAY_FRQ_PRD_LEG2" IS 'Fixed rate payment frequency period leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FIX_RATE_PAY_FRQ_MULT_LEG2" IS 'Fixed rate payment frequency period multiplier leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FLOAT_RATE_ID_LEG2" IS 'Identifier of the floating rate of leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FLOAT_RATE_INDICATOR_LEG2" IS 'Indicator of the floating rate of leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FLOAT_RATE_NAME_LEG2" IS 'Name of the floating rate of leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FLOAT_RATE_DAY_CNT_CONV_S2" IS 'Floating rate day count convention of leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FLOAT_RATE_PAY_FRQ_PRD_S2" IS 'Floating rate payment frequency period of leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FLOAT_RATE_PAY_FRQ_MULT_S2" IS 'Floating rate payment frequency period multiplier of leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FLOAT_RATE_REF_PRD_TIME_S2" IS 'Floating rate reference period of leg 2 - time period';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FLOAT_RATE_REF_PRD_MULT_S2" IS 'Floating rate reference period of leg 2 - multiplier';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FLOAT_RATE_RST_FRQ_PRD_S2" IS 'Floating rate reset frequency period of leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FLOAT_RATE_RST_FRQ_MULT_S2" IS 'Floating rate reset frequency multiplier of leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SPREAD_TYPE_LEG2" IS 'Spread of leg 2 - Type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SPREAD_LEG2" IS 'Spread of leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SPREAD_CCY_LEG2" IS 'Spread currency of leg 2';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PKG_SPREAD_TYPE" IS 'Package transaction spread - Type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PKG_TRANSACTION_SPREAD" IS 'Package transaction spread';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PKG_TRANSACTION_SPREAD_CCY" IS 'Package transaction spread currency';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."EXCHANGE_RATE" IS 'Exchange rate 1';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."FWD_EXCHANGE_RATE" IS 'Forward exchange rate';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."EXCHANGE_RATE_BASIS" IS 'Exchange rate basis';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."BASE_PRODUCT" IS 'Base product';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SUB_PRODUCT" IS 'Sub-product';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SUB_PRODUCT2" IS 'Further sub-product';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."DELIVERY_POINT" IS 'Delivery point or zone';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."INTERCONNCT_POINT" IS 'Interconnection Point';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."LOAD_TYPE" IS 'Load type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."DELIVERY_START_TIME" IS 'Delivery interval start time';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."DELIVERY_END_TIME" IS 'Delivery interval end time';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."DELIVERY_START_DATE" IS 'Delivery start date';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."DELIVERY_END_DATE" IS 'Delivery end date';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."DURATION" IS 'Duration';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."DAYS_OF_WEEK" IS 'Days of the week';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."DELIVERY_CAPACITY" IS 'Delivery capacity';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."QTY_UNIT" IS 'Quantity Unit';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PRICE_TIME_INTERVL_QTY" IS 'Price/time interval quantity';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PRICE_TIME_INTERVL_QTY_CCY" IS 'Currency of the price/time interval quantity';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."OPTION_TYPE" IS 'Option type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."OPTION_STYLE" IS 'Option style';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."STRIKE_PRICE_TYPE" IS 'Strike price - Type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."STRIKE_PRICE" IS 'Strike price';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."STRIKE_PRICE_CCY" IS 'Strike price - Currency';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."STRIKE_PRICE_EFF_DATE" IS 'Effective date of the strike price';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."STRIKE_PRICE_END_DATE" IS 'End date of the strike price';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."STRIKE_PRICE_IN_EFFCT_TYPE" IS 'Strike price in effect on associated effective date - Type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."STRIKE_PRICE_IN_EFFCT_DATE" IS 'Strike price in effect on associated effective date';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."STRIKE_PRICE_IN_EFFCT_CCY" IS 'Strike price in effect on associated effective date - Currency';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."STRKE_PRICE_CCY_PAIR" IS 'Strike price currency/currency pair';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."OPTION_PREMIUM_AMT" IS 'Option premium amount';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."OPTION_PREMIUM_CCY" IS 'Option premium currency';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."OPTION_PREMIUM_PAY_DATE" IS 'Option premium payment date';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."UNDERLYING_MATURITY_DATE" IS 'Maturity date of the underlying';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SENIORITY" IS 'Seniority';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."REF_ENTITY" IS 'Reference entity';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PAY_FRQ" IS 'Frequency of payment';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CALC_BASIS" IS 'Calculation Basis';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."SERIES" IS 'Series';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."VERSION" IS 'Version';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."INDEX_FACTOR" IS 'Index factor';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."TRANCHE" IS 'Tranche';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CDS_INDEX_ATTACH_POINT" IS 'CDS index attachment point';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CDS_INDEX_DETACH_POINT" IS 'CDS index detachment point';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."ACTION_TYPE" IS 'Action type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."EVENT_TYPE" IS 'Event type';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."LEVEL_VAL" IS 'Level';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."RECON_FLG" IS 'Reconciliation Flag';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."PAIR_SRC" IS 'Pair Source';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."TRADE_REF_ID" IS 'Trade Reference ID';
   COMMENT ON COLUMN "SDH"."TB_TRADE_MUREX_LST_OPT"."CNT_VERSION" IS 'Contract number';
   COMMENT ON TABLE "SDH"."TB_TRADE_MUREX_LST_OPT"  IS 'Murex ETD Revcon trades (Listed Options)';
--------------------------------------------------------
--  Constraints for Table TB_TRADE_MUREX_LST_OPT
--------------------------------------------------------

  ALTER TABLE "SDH"."TB_TRADE_MUREX_LST_OPT" MODIFY ("SYS_CREAT_DTMS" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_TRADE_MUREX_LST_OPT" MODIFY ("SYS_CREAT_PROCSS_USR_ID" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_TRADE_MUREX_LST_OPT" MODIFY ("SYS_PARTITION_ID" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_TRADE_MUREX_LST_OPT" MODIFY ("SYS_VALUE_DATE" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_TRADE_MUREX_LST_OPT" MODIFY ("SYS_VALUE_TM" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_TRADE_MUREX_LST_OPT" MODIFY ("SYS_LOAD_TIMELN_VAL" NOT NULL ENABLE);
  ALTER TABLE "SDH"."TB_TRADE_MUREX_LST_OPT" MODIFY ("TRR_SID" NOT NULL ENABLE);
